package ZeuS.Config;

import java.util.HashMap;
import java.util.Map;
import java.util.logging.Logger;

public enum enum_skill_path_name {
	SKILL_1_ABYSSAL_POWER("Abyssal Power",1474,1,"Power"),
	SKILL_1_ACCURACY("Accuracy",256,1,"Cost"),
	SKILL_2_ACUMEN("Acumen",1085,2,"Cost"),
	SKILL_1_ACUMEN("Acumen",1085,1,"Time"),
	SKILL_2_ADVANCED_BLOCK("Advanced Block",1304,2,"Cost"),
	SKILL_1_ADVANCED_BLOCK("Advanced Block",1304,1,"Time"),
	SKILL_1_AEGIS_STANCE("Aegis Stance",318,1,"Decrease Penalty"),
	SKILL_3_AGGRESSION("Aggression",28,3,"Attack"),
	SKILL_2_AGGRESSION("Aggression",28,2,"Defense"),
	SKILL_1_AGGRESSION("Aggression",28,1,"Power"),
	SKILL_1_AGILE_MOVEMENT("Agile Movement",319,1,"Power"),
	SKILL_2_AGILITY("Agility",1087,2,"Cost"),
	SKILL_1_AGILITY("Agility",1087,1,"Time"),
	SKILL_1_ANCHOR("Anchor",1170,1,"Chance"),
	SKILL_2_ANCHOR("Anchor",1170,2,"Cost"),
	SKILL_1_ANCIENT_SWORD_MASTERY("Ancient Sword Mastery",472,1,"Power"),
	SKILL_2_ANCIENT_SWORD_MASTERY("Ancient Sword Mastery",472,2,"Swiftness"),
	SKILL_2_ANGELIC_ICON("Angelic Icon",406,2,"Cost"),
	SKILL_1_ANGELIC_ICON("Angelic Icon",406,1,"Power"),
	SKILL_3_ANGELIC_ICON("Angelic Icon",406,3,"Recycle"),
	SKILL_4_ANGELIC_ICON("Angelic Icon",406,4,"Time"),
	SKILL_2_ANNIHILATION_CIRCLE("Annihilation Circle",1438,2,"Cost"),
	SKILL_3_ANNIHILATION_CIRCLE("Annihilation Circle",1438,3,"Dark Attack"),
	SKILL_4_ANNIHILATION_CIRCLE("Annihilation Circle",1438,4,"Duel"),
	SKILL_1_ANNIHILATION_CIRCLE("Annihilation Circle",1438,1,"Power"),
	SKILL_1_ANTI_MAGIC("Anti Magic",146,1,"Power"),
	SKILL_1_APPETITE_FOR_DESTRUCTION("Appetite for Destruction",1476,1,"Cost"),
	SKILL_3_APPETITE_FOR_DESTRUCTION("Appetite for Destruction",1476,3,"Recycle"),
	SKILL_2_APPETITE_FOR_DESTRUCTION("Appetite for Destruction",1476,2,"Time"),
	SKILL_2_AQUA_SPLASH("Aqua Splash",1295,2,"Cost"),
	SKILL_1_AQUA_SPLASH("Aqua Splash",1295,1,"Power"),
	SKILL_3_AQUA_SPLASH("Aqua Splash",1295,3,"Water Attack"),
	SKILL_1_ARCANE_AGILITY("Arcane Agility",338,1,"Power"),
	SKILL_1_ARCANE_CHAOS("Arcane Chaos",1338,1,"Chance"),
	SKILL_2_ARCANE_CHAOS("Arcane Chaos",1338,2,"Cost"),
	SKILL_3_ARCANE_DISRUPTION("Arcane Disruption",1386,3,"Chance"),
	SKILL_2_ARCANE_DISRUPTION("Arcane Disruption",1386,2,"Cost"),
	SKILL_1_ARCANE_DISRUPTION("Arcane Disruption",1386,1,"Power"),
	SKILL_1_ARCANE_POWER("Arcane Power",337,1,"Power"),
	SKILL_2_ARCANE_PROTECTION("Arcane Protection",1354,2,"Cost"),
	SKILL_1_ARCANE_PROTECTION("Arcane Protection",1354,1,"Time"),
	SKILL_1_ARCANE_ROAR("Arcane Roar",433,1,"Power"),
	SKILL_1_ARCANE_WISDOM("Arcane Wisdom",336,1,"Power"),
	SKILL_1_ARCHERY("Archery",431,1,"Power"),
	SKILL_3_ARMOR_CRUSH("Armor Crush",362,3,"Chance"),
	SKILL_2_ARMOR_CRUSH("Armor Crush",362,2,"Cost"),
	SKILL_1_ARMOR_CRUSH("Armor Crush",362,1,"Power"),
	SKILL_2_ARREST("Arrest",402,2,"Chance"),
	SKILL_1_ARREST("Arrest",402,1,"Power"),
	SKILL_2_ASSASSIN_SERVITOR("Assassin Servitor",1348,2,"Cost"),
	SKILL_1_ASSASSIN_SERVITOR("Assassin Servitor",1348,1,"Time"),
	SKILL_1_ASSASSINATION("Assassination",432,1,"Power"),
	SKILL_2_AURA_BOLT("Aura Bolt",1275,2,"Cost"),
	SKILL_3_AURA_BOLT("Aura Bolt",1275,3,"Duel"),
	SKILL_1_AURA_BOLT("Aura Bolt",1275,1,"Power"),
	SKILL_2_AURA_FLARE("Aura Flare",1231,2,"Cost"),
	SKILL_1_AURA_FLARE("Aura Flare",1231,1,"Power"),
	SKILL_2_AURA_FLASH("Aura Flash",1417,2,"Chance"),
	SKILL_1_AURA_FLASH("Aura Flash",1417,1,"Power"),
	SKILL_2_AURA_OF_HATE("Aura of Hate",18,2,"Defense"),
	SKILL_1_AURA_OF_HATE("Aura of Hate",18,1,"Power"),
	SKILL_2_AURA_SYMPHONY("Aura Symphony",1288,2,"Cost"),
	SKILL_3_AURA_SYMPHONY("Aura Symphony",1288,3,"Duel"),
	SKILL_1_AURA_SYMPHONY("Aura Symphony",1288,1,"Power"),
	SKILL_2_BACKSTAB("Backstab",30,2,"Cost"),
	SKILL_7_BACKSTAB("Backstab",30,7,"Duel"),
	SKILL_6_BACKSTAB("Backstab",30,6,"Earth Attack"),
	SKILL_3_BACKSTAB("Backstab",30,3,"Fire Attack"),
	SKILL_1_BACKSTAB("Backstab",30,1,"Power"),
	SKILL_4_BACKSTAB("Backstab",30,4,"Water Attack"),
	SKILL_5_BACKSTAB("Backstab",30,5,"Wind Attack"),
	SKILL_3_BANISH_SERAPH("Banish Seraph",450,3,"Attack"),
	SKILL_2_BANISH_SERAPH("Banish Seraph",450,2,"Chance"),
	SKILL_1_BANISH_SERAPH("Banish Seraph",450,1,"Cost"),
	SKILL_4_BANISH_SERAPH("Banish Seraph",450,4,"Dark Attack"),
	SKILL_3_BANISH_UNDEAD("Banish Undead",405,3,"Attack"),
	SKILL_2_BANISH_UNDEAD("Banish Undead",405,2,"Chance"),
	SKILL_1_BANISH_UNDEAD("Banish Undead",405,1,"Cost"),
	SKILL_4_BANISH_UNDEAD("Banish Undead",405,4,"Holy Attack"),
	SKILL_2_BATTLE_ROAR("Battle Roar",121,2,"Attack"),
	SKILL_1_BATTLE_ROAR("Battle Roar",121,1,"Recycle"),
	SKILL_2_BENEDICTION("Benediction",1271,2,"Bravery"),
	SKILL_1_BENEDICTION("Benediction",1271,1,"Cost"),
	SKILL_2_BERSERKER_SPIRIT("Berserker Spirit",1062,2,"Cost"),
	SKILL_1_BERSERKER_SPIRIT("Berserker Spirit",1062,1,"Time"),
	SKILL_1_BINDING_TRAP("Binding Trap",518,1,"Power"),
	SKILL_2_BINDING_TRAP("Binding Trap",518,2,"Recycle"),
	SKILL_2_BLADE_RUSH("Blade Rush",495,2,"Chance"),
	SKILL_3_BLADE_RUSH("Blade Rush",495,3,"Cost"),
	SKILL_4_BLADE_RUSH("Blade Rush",495,4,"Duel"),
	SKILL_1_BLADE_RUSH("Blade Rush",495,1,"Power"),
	SKILL_2_BLAZING_CIRCLE("Blazing Circle",1171,2,"Cost"),
	SKILL_3_BLAZING_CIRCLE("Blazing Circle",1171,3,"Fire Attack"),
	SKILL_1_BLAZING_CIRCLE("Blazing Circle",1171,1,"Power"),
	SKILL_2_BLAZING_SKIN("Blazing Skin",1232,2,"Cost"),
	SKILL_3_BLAZING_SKIN("Blazing Skin",1232,3,"Defense"),
	SKILL_4_BLAZING_SKIN("Blazing Skin",1232,4,"Resist Fire"),
	SKILL_1_BLAZING_SKIN("Blazing Skin",1232,1,"Time"),
	SKILL_1_BLEED("Bleed",96,1,"Cost"),
	SKILL_3_BLEED("Bleed",96,3,"Power"),
	SKILL_2_BLEED("Bleed",96,2,"Sap"),
	SKILL_3_BLEEDING_SHOT("Bleeding Shot",509,3,"Chance"),
	SKILL_2_BLEEDING_SHOT("Bleeding Shot",509,2,"Cost"),
	SKILL_1_BLEEDING_SHOT("Bleeding Shot",509,1,"Power"),
	SKILL_2_BLESS_SHIELD("Bless Shield",1243,2,"Cost"),
	SKILL_1_BLESS_SHIELD("Bless Shield",1243,1,"Time"),
	SKILL_2_BLESS_THE_BODY("Bless the Body",1045,2,"Cost"),
	SKILL_1_BLESS_THE_BODY("Bless the Body",1045,1,"Time"),
	SKILL_2_BLESS_THE_SOUL("Bless the Soul",1048,2,"Cost"),
	SKILL_1_BLESS_THE_SOUL("Bless the Soul",1048,1,"Time"),
	SKILL_1_BLESSED_BLOOD("Blessed Blood",1531,1,"Power"),
	SKILL_2_BLESSED_BLOOD("Blessed Blood",1531,2,"Time"),
	SKILL_2_BLESSINGS_OF_PAAGRIO("Blessings of Pa agrio",1005,2,"Cost"),
	SKILL_1_BLESSINGS_OF_PAAGRIO("Blessings of Pa agrio",1005,1,"Time"),
	SKILL_2_BLINDING_BLOW("Blinding Blow",321,2,"Cost"),
	SKILL_1_BLINDING_BLOW("Blinding Blow",321,1,"Power"),
	SKILL_1_BLINK("Blink",1448,1,"Cost"),
	SKILL_2_BLINK("Blink",1448,2,"Distance"),
	SKILL_2_BLIZZARD("Blizzard",1290,2,"Cost"),
	SKILL_1_BLIZZARD("Blizzard",1290,1,"Power"),
	SKILL_3_BLIZZARD("Blizzard",1290,3,"Water Attack"),
	SKILL_1_BLOCK_SHIELD("Block Shield",1358,1,"Chance"),
	SKILL_2_BLOCK_SHIELD("Block Shield",1358,2,"Cost"),
	SKILL_1_BLOCK_WIND_WALK("Block Wind Walk",1359,1,"Chance"),
	SKILL_2_BLOCK_WIND_WALK("Block Wind Walk",1359,2,"Cost"),
	SKILL_1_BLUFF("Bluff",358,1,"Chance"),
	SKILL_2_BODY_OF_AVATAR("Body of Avatar",1311,2,"Cost"),
	SKILL_1_BODY_OF_AVATAR("Body of Avatar",1311,1,"Time"),
	SKILL_3_BODY_TO_MIND("Body To Mind",1157,3,"Bravery"),
	SKILL_2_BODY_TO_MIND("Body To Mind",1157,2,"Cost"),
	SKILL_1_BODY_TO_MIND("Body To Mind",1157,1,"Power"),
	SKILL_1_BOOST_ATTACK_SPEED("Boost Attack Speed",168,1,"Power"),
	SKILL_1_BOOST_EVASION("Boost Evasion",198,1,"Power"),
	SKILL_4_BOOST_HP("Boost HP",211,4,"Bravery"),
	SKILL_3_BOOST_HP("Boost HP",211,3,"Life"),
	SKILL_1_BOOST_HP("Boost HP",211,1,"Power"),
	SKILL_1_BOOST_MANA("Boost Mana",213,1,"Power"),
	SKILL_1_BOW_MASTERY("Bow Mastery",208,1,"Power"),
	SKILL_2_BOW_MASTERY("Bow Mastery",208,2,"Swiftness"),
	SKILL_1_BRAVEHEART("Braveheart",440,1,"Power"),
	SKILL_2_BRIGHT_SERVITOR("Bright Servitor",1145,2,"Cost"),
	SKILL_1_BRIGHT_SERVITOR("Bright Servitor",1145,1,"Time"),
	SKILL_1_BURNING_CHOP("Burning Chop",927,1,"Power"),
	SKILL_2_BURNING_FIST("Burning Fist",280,2,"Cost"),
	SKILL_3_BURNING_FIST("Burning Fist",280,3,"Fire Attack"),
	SKILL_1_BURNING_FIST("Burning Fist",280,1,"Power"),
	SKILL_2_BURST_SHOT("Burst Shot",24,2,"Cost"),
	SKILL_3_BURST_SHOT("Burst Shot",24,3,"Fire Attack"),
	SKILL_1_BURST_SHOT("Burst Shot",24,1,"Power"),
	SKILL_2_CHAIN_LIGHTNING("Chain Lightning",1450,2,"Cost"),
	SKILL_4_CHAIN_LIGHTNING("Chain Lightning",1450,4,"Duel"),
	SKILL_1_CHAIN_LIGHTNING("Chain Lightning",1450,1,"Power"),
	SKILL_3_CHAIN_LIGHTNING("Chain Lightning",1450,3,"Wind Attack"),
	SKILL_2_CHANT_OF_BATTLE("Chant of Battle",1007,2,"Cost"),
	SKILL_1_CHANT_OF_BATTLE("Chant of Battle",1007,1,"Time"),
	SKILL_2_CHANT_OF_EAGLE("Chant of Eagle",1309,2,"Cost"),
	SKILL_1_CHANT_OF_EAGLE("Chant of Eagle",1309,1,"Time"),
	SKILL_2_CHANT_OF_EVASION("Chant of Evasion",1252,2,"Cost"),
	SKILL_1_CHANT_OF_EVASION("Chant of Evasion",1252,1,"Time"),
	SKILL_2_CHANT_OF_FIRE("Chant of Fire",1006,2,"Cost"),
	SKILL_1_CHANT_OF_FIRE("Chant of Fire",1006,1,"Time"),
	SKILL_2_CHANT_OF_FURY("Chant of Fury",1251,2,"Cost"),
	SKILL_1_CHANT_OF_FURY("Chant of Fury",1251,1,"Time"),
	SKILL_2_CHANT_OF_LIFE("Chant of Life",1229,2,"Cost"),
	SKILL_1_CHANT_OF_LIFE("Chant of Life",1229,1,"Power"),
	SKILL_2_CHANT_OF_PREDATOR("Chant of Predator",1308,2,"Cost"),
	SKILL_1_CHANT_OF_PREDATOR("Chant of Predator",1308,1,"Time"),
	SKILL_2_CHANT_OF_PROTECTION("Chant of Protection",1461,2,"Cost"),
	SKILL_1_CHANT_OF_PROTECTION("Chant of Protection",1461,1,"Time"),
	SKILL_2_CHANT_OF_RAGE("Chant of Rage",1253,2,"Cost"),
	SKILL_1_CHANT_OF_RAGE("Chant of Rage",1253,1,"Time"),
	SKILL_2_CHANT_OF_REVENGE("Chant of Revenge",1284,2,"Cost"),
	SKILL_1_CHANT_OF_REVENGE("Chant of Revenge",1284,1,"Time"),
	SKILL_2_CHANT_OF_SHIELDING("Chant of Shielding",1009,2,"Cost"),
	SKILL_1_CHANT_OF_SHIELDING("Chant of Shielding",1009,1,"Time"),
	SKILL_2_CHANT_OF_SPIRIT("Chant of Spirit",1362,2,"Cost"),
	SKILL_1_CHANT_OF_SPIRIT("Chant of Spirit",1362,1,"Time"),
	SKILL_2_CHANT_OF_VAMPIRE("Chant of Vampire",1310,2,"Cost"),
	SKILL_1_CHANT_OF_VAMPIRE("Chant of Vampire",1310,1,"Time"),
	SKILL_2_CHANT_OF_VICTORY("Chant of Victory",1363,2,"Cost"),
	SKILL_3_CHANT_OF_VICTORY("Chant of Victory",1363,3,"Decrease Penalty"),
	SKILL_1_CHANT_OF_VICTORY("Chant of Victory",1363,1,"Time"),
	SKILL_2_CHECKMATE("Checkmate",506,2,"Cost"),
	SKILL_3_CHECKMATE("Checkmate",506,3,"Dark Attack"),
	SKILL_4_CHECKMATE("Checkmate",506,4,"Duel"),
	SKILL_1_CHECKMATE("Checkmate",506,1,"Power"),
	SKILL_1_CLARITY("Clarity",1397,1,"Power Physical"),
	SKILL_2_CLARITY("Clarity",1397,2,"Power Magical"),
	SKILL_3_CLARITY("Clarity",1397,3,"Power Dance/Song"),
	SKILL_4_CLARITY("Clarity",1397,4,"Time"),
	SKILL_2_CONCENTRATION("Concentration",1078,2,"Cost"),
	SKILL_1_CONCENTRATION("Concentration",1078,1,"Time"),
	SKILL_2_CONTAGION("Contagion",498,2,"Cost"),
	SKILL_3_CONTAGION("Contagion",498,3,"Duel"),
	SKILL_1_CONTAGION("Contagion",498,1,"Power"),
	SKILL_2_CORPSE_BURST("Corpse Burst",1155,2,"Cost"),
	SKILL_1_CORPSE_BURST("Corpse Burst",1155,1,"Power"),
	SKILL_2_CORPSE_LIFE_DRAIN("Corpse Life Drain",1151,2,"Bravery"),
	SKILL_1_CORPSE_LIFE_DRAIN("Corpse Life Drain",1151,1,"Power"),
	SKILL_2_COUNT_OF_FIRE("Count of Fire",1452,2,"Cost"),
	SKILL_3_COUNT_OF_FIRE("Count of Fire",1452,3,"Fire Attack"),
	SKILL_1_COUNT_OF_FIRE("Count of Fire",1452,1,"Power"),
	SKILL_1_CRIPPLE("Cripple",95,1,"Chance"),
	SKILL_2_CRIPPLE("Cripple",95,2,"Cost"),
	SKILL_2_CRITICAL_BLOW("Critical Blow",409,2,"Cost"),
	SKILL_7_CRITICAL_BLOW("Critical Blow",409,7,"Duel"),
	SKILL_6_CRITICAL_BLOW("Critical Blow",409,6,"Earth Attack"),
	SKILL_3_CRITICAL_BLOW("Critical Blow",409,3,"Fire Attack"),
	SKILL_1_CRITICAL_BLOW("Critical Blow",409,1,"Power"),
	SKILL_4_CRITICAL_BLOW("Critical Blow",409,4,"Water Attack"),
	SKILL_5_CRITICAL_BLOW("Critical Blow",409,5,"Wind Attack"),
	SKILL_1_CRITICAL_CHANCE("Critical Chance",137,1,"Power"),
	SKILL_1_CRITICAL_DAMAGE("Critical Damage",193,1,"Power"),
	SKILL_1_CRITICAL_SENSE("Critical Sense",626,1,"Power"),
	SKILL_1_CROSSBOW_MASTERY("Crossbow Mastery",473,1,"Power"),
	SKILL_2_CROSSBOW_MASTERY("Crossbow Mastery",473,2,"Swiftness"),
	SKILL_2_CRUSH_OF_DOOM("Crush of Doom",315,2,"Cost"),
	SKILL_7_CRUSH_OF_DOOM("Crush of Doom",315,7,"Duel"),
	SKILL_6_CRUSH_OF_DOOM("Crush of Doom",315,6,"Earth Attack"),
	SKILL_3_CRUSH_OF_DOOM("Crush of Doom",315,3,"Fire Attack"),
	SKILL_1_CRUSH_OF_DOOM("Crush of Doom",315,1,"Power"),
	SKILL_4_CRUSH_OF_DOOM("Crush of Doom",315,4,"Water Attack"),
	SKILL_5_CRUSH_OF_DOOM("Crush of Doom",315,5,"Wind Attack"),
	SKILL_2_CRUSH_OF_PAIN("Crush of Pain",497,2,"Cost"),
	SKILL_7_CRUSH_OF_PAIN("Crush of Pain",497,7,"Duel"),
	SKILL_6_CRUSH_OF_PAIN("Crush of Pain",497,6,"Earth Attack"),
	SKILL_3_CRUSH_OF_PAIN("Crush of Pain",497,3,"Fire Attack"),
	SKILL_1_CRUSH_OF_PAIN("Crush of Pain",497,1,"Power"),
	SKILL_4_CRUSH_OF_PAIN("Crush of Pain",497,4,"Water Attack"),
	SKILL_5_CRUSH_OF_PAIN("Crush of Pain",497,5,"Wind Attack"),
	SKILL_1_CURSE_CHAOS("Curse Chaos",1222,1,"Chance"),
	SKILL_2_CURSE_CHAOS("Curse Chaos",1222,2,"Cost"),
	SKILL_3_CURSE_CHAOS("Curse Chaos",1222,3,"Power"),
	SKILL_2_CURSE_DEATH_LINK("Curse Death Link",1159,2,"Cost"),
	SKILL_1_CURSE_DEATH_LINK("Curse Death Link",1159,1,"Power"),
	SKILL_1_CURSE_DISEASE("Curse Disease",1269,1,"Chance"),
	SKILL_2_CURSE_DISEASE("Curse Disease",1269,2,"Cost"),
	SKILL_3_CURSE_DISEASE("Curse Disease",1269,3,"Power"),
	SKILL_2_CURSE_FEAR("Curse Fear",1169,2,"Chance"),
	SKILL_1_CURSE_FEAR("Curse Fear",1169,1,"Cost"),
	SKILL_1_CURSE_GLOOM("Curse Gloom",1263,1,"Chance"),
	SKILL_2_CURSE_GLOOM("Curse Gloom",1263,2,"Cost"),
	SKILL_1_CURSE_OF_ABYSS("Curse of Abyss",1337,1,"Chance"),
	SKILL_2_CURSE_OF_ABYSS("Curse of Abyss",1337,2,"Cost"),
	SKILL_1_CURSE_OF_DOOM("Curse of Doom",1336,1,"Chance"),
	SKILL_2_CURSE_OF_DOOM("Curse of Doom",1336,2,"Cost"),
	SKILL_2_CURSE_OF_LIFE_FLOW("Curse of Life Flow",1511,2,"Chance"),
	SKILL_1_CURSE_OF_LIFE_FLOW("Curse of Life Flow",1511,1,"Time"),
	SKILL_1_CURSE_WEAKNESS("Curse Weakness",1164,1,"Chance"),
	SKILL_2_CURSE_WEAKNESS("Curse Weakness",1164,2,"Cost"),
	SKILL_4_CURSE_WEAKNESS("Curse Weakness",1164,4,"Defense"),
	SKILL_3_CURSE_WEAKNESS("Curse Weakness",1164,3,"Modify Speed"),
	SKILL_2_DAGGER_MASTERY("Dagger Mastery",209,2,"Modify Critical"),
	SKILL_1_DAGGER_MASTERY("Dagger Mastery",209,1,"Power"),
	SKILL_2_DANCE_OF_ALIGNMENT("Dance of Alignment",530,2,"Cost"),
	SKILL_1_DANCE_OF_ALIGNMENT("Dance of Alignment",530,1,"Time"),
	SKILL_2_DANCE_OF_AQUA_GUARD("Dance of Aqua Guard",307,2,"Cost"),
	SKILL_1_DANCE_OF_AQUA_GUARD("Dance of Aqua Guard",307,1,"Time"),
	SKILL_2_DANCE_OF_BLADE_STORM("Dance of Blade Storm",765,2,"Cost"),
	SKILL_1_DANCE_OF_BLADE_STORM("Dance of Blade Storm",765,1,"Time"),
	SKILL_2_DANCE_OF_CONCENTRATION("Dance of Concentration",276,2,"Cost"),
	SKILL_1_DANCE_OF_CONCENTRATION("Dance of Concentration",276,1,"Time"),
	SKILL_2_DANCE_OF_EARTH_GUARD("Dance of Earth Guard",309,2,"Cost"),
	SKILL_1_DANCE_OF_EARTH_GUARD("Dance of Earth Guard",309,1,"Time"),
	SKILL_2_DANCE_OF_FIRE("Dance of Fire",274,2,"Cost"),
	SKILL_1_DANCE_OF_FIRE("Dance of Fire",274,1,"Time"),
	SKILL_2_DANCE_OF_FURY("Dance of Fury",275,2,"Cost"),
	SKILL_1_DANCE_OF_FURY("Dance of Fury",275,1,"Time"),
	SKILL_2_DANCE_OF_INSPIRATION("Dance of Inspiration",272,2,"Cost"),
	SKILL_1_DANCE_OF_INSPIRATION("Dance of Inspiration",272,1,"Time"),
	SKILL_2_DANCE_OF_LIGHT("Dance of Light",277,2,"Cost"),
	SKILL_1_DANCE_OF_LIGHT("Dance of Light",277,1,"Time"),
	SKILL_1_DANCE_OF_MEDUSA("Dance of Medusa",367,1,"Chance"),
	SKILL_2_DANCE_OF_MEDUSA("Dance of Medusa",367,2,"Time"),
	SKILL_2_DANCE_OF_PROTECTION("Dance of Protection",311,2,"Cost"),
	SKILL_1_DANCE_OF_PROTECTION("Dance of Protection",311,1,"Time"),
	SKILL_2_DANCE_OF_SHADOWS("Dance of Shadows",366,2,"Cost"),
	SKILL_1_DANCE_OF_SHADOWS("Dance of Shadows",366,1,"Time"),
	SKILL_2_DANCE_OF_SIREN("Dance of Siren",365,2,"Cost"),
	SKILL_1_DANCE_OF_SIREN("Dance of Siren",365,1,"Time"),
	SKILL_2_DANCE_OF_THE_MYSTIC("Dance of the Mystic",273,2,"Cost"),
	SKILL_1_DANCE_OF_THE_MYSTIC("Dance of the Mystic",273,1,"Time"),
	SKILL_2_DANCE_OF_THE_VAMPIRE("Dance of the Vampire",310,2,"Cost"),
	SKILL_1_DANCE_OF_THE_VAMPIRE("Dance of the Vampire",310,1,"Time"),
	SKILL_2_DANCE_OF_THE_WARRIOR("Dance of the Warrior",271,2,"Cost"),
	SKILL_1_DANCE_OF_THE_WARRIOR("Dance of the Warrior",271,1,"Time"),
	SKILL_3_DARK_FLAME("Dark Flame",1437,3,"Chance"),
	SKILL_2_DARK_FLAME("Dark Flame",1437,2,"Cost"),
	SKILL_4_DARK_FLAME("Dark Flame",1437,4,"Dark Attack"),
	SKILL_1_DARK_FLAME("Dark Flame",1437,1,"Power"),
	SKILL_5_DARK_FLAME("Dark Flame",1437,5,"Weaken Dark"),
	SKILL_2_DARK_SMASH("Dark Smash",477,2,"Cost"),
	SKILL_3_DARK_SMASH("Dark Smash",477,3,"Dark Attack"),
	SKILL_4_DARK_SMASH("Dark Smash",477,4,"Duel"),
	SKILL_1_DARK_SMASH("Dark Smash",477,1,"Power"),
	SKILL_3_DARK_VORTEX("Dark Vortex",1343,3,"Chance"),
	SKILL_2_DARK_VORTEX("Dark Vortex",1343,2,"Cost"),
	SKILL_4_DARK_VORTEX("Dark Vortex",1343,4,"Dark Attack"),
	SKILL_1_DARK_VORTEX("Dark Vortex",1343,1,"Power"),
	SKILL_1_DARK_WEAPON("Dark Weapon",1443,1,"Power"),
	SKILL_2_DARK_WEAPON("Dark Weapon",1443,2,"Time"),
	SKILL_1_DEAD_EYE("Dead Eye",414,1,"Power"),
	SKILL_2_DEADLY_BLOW("Deadly Blow",263,2,"Cost"),
	SKILL_7_DEADLY_BLOW("Deadly Blow",263,7,"Duel"),
	SKILL_6_DEADLY_BLOW("Deadly Blow",263,6,"Earth Attack"),
	SKILL_3_DEADLY_BLOW("Deadly Blow",263,3,"Fire Attack"),
	SKILL_1_DEADLY_BLOW("Deadly Blow",263,1,"Power"),
	SKILL_4_DEADLY_BLOW("Deadly Blow",263,4,"Water Attack"),
	SKILL_5_DEADLY_BLOW("Deadly Blow",263,5,"Wind Attack"),
	SKILL_2_DEADLY_ROULETTE("Deadly Roulette",510,2,"Cost"),
	SKILL_1_DEADLY_ROULETTE("Deadly Roulette",510,1,"Power"),
	SKILL_2_DEATH_MARK("Death Mark",1435,2,"Chance"),
	SKILL_1_DEATH_MARK("Death Mark",1435,1,"Power"),
	SKILL_2_DEATH_SPIKE("Death Spike",1148,2,"Cost"),
	SKILL_1_DEATH_SPIKE("Death Spike",1148,1,"Power"),
	SKILL_2_DEATH_WHISPER("Death Whisper",1242,2,"Cost"),
	SKILL_1_DEATH_WHISPER("Death Whisper",1242,1,"Time"),
	SKILL_1_DECOY("Decoy",525,1,"Cost"),
	SKILL_3_DECOY("Decoy",525,3,"Power"),
	SKILL_2_DECOY("Decoy",525,2,"Recycle"),
	SKILL_2_DECREASE_WEIGHT("Decrease Weight",1257,2,"Cost"),
	SKILL_1_DECREASE_WEIGHT("Decrease Weight",1257,1,"Time"),
	SKILL_2_DEFLECT_ARROW("Deflect Arrow",112,2,"AdditionalDefense"),
	SKILL_1_DEFLECT_ARROW("Deflect Arrow",112,1,"Time"),
	SKILL_2_DEMON_WIND("Demon Wind",1291,2,"Cost"),
	SKILL_1_DEMON_WIND("Demon Wind",1291,1,"Power"),
	SKILL_3_DEMON_WIND("Demon Wind",1291,3,"Wind Attack"),
	SKILL_2_DIAMOND_DUST("Diamond Dust",1454,2,"Cost"),
	SKILL_1_DIAMOND_DUST("Diamond Dust",1454,1,"Power"),
	SKILL_3_DIAMOND_DUST("Diamond Dust",1454,3,"Water Attack"),
	SKILL_1_DISARM("Disarm",485,1,"Chance"),
	SKILL_2_DISARM("Disarm",485,2,"Time"),
	SKILL_1_DIVINE_AURA("Divine Aura",107,1,"Chance"),
	SKILL_2_DIVINE_AURA("Divine Aura",107,2,"Cost"),
	SKILL_3_DIVINE_AURA("Divine Aura",107,3,"Modify Critical"),
	SKILL_2_DIVINE_BLESSING("Divine Blessing",262,2,"Cost"),
	SKILL_3_DIVINE_BLESSING("Divine Blessing",262,3,"Cure Poison"),
	SKILL_4_DIVINE_BLESSING("Divine Blessing",262,4,"Heal Bleeding"),
	SKILL_1_DIVINE_BLESSING("Divine Blessing",262,1,"Power"),
	SKILL_1_DIVINE_LORE("Divine Lore",436,1,"Power"),
	SKILL_2_DIVINE_POWER("Divine Power",1459,2,"Cost"),
	SKILL_1_DIVINE_POWER("Divine Power",1459,1,"Power"),
	SKILL_2_DIVINE_PROTECTION("Divine Protection",1353,2,"Cost"),
	SKILL_1_DIVINE_PROTECTION("Divine Protection",1353,1,"Time"),
	SKILL_2_DIVINE_STRIKE("Divine Strike",49,2,"Cost"),
	SKILL_3_DIVINE_STRIKE("Divine Strike",49,3,"Holy Attack"),
	SKILL_1_DIVINE_STRIKE("Divine Strike",49,1,"Power"),
	SKILL_2_DOUBLE_SHOT("Double Shot",19,2,"Cost"),
	SKILL_7_DOUBLE_SHOT("Double Shot",19,7,"Duel"),
	SKILL_6_DOUBLE_SHOT("Double Shot",19,6,"Earth Attack"),
	SKILL_3_DOUBLE_SHOT("Double Shot",19,3,"Fire Attack"),
	SKILL_1_DOUBLE_SHOT("Double Shot",19,1,"Power"),
	SKILL_4_DOUBLE_SHOT("Double Shot",19,4,"Water Attack"),
	SKILL_5_DOUBLE_SHOT("Double Shot",19,5,"Wind Attack"),
	SKILL_2_DOUBLE_SONIC_SLASH("Double Sonic Slash",5,2,"Cost"),
	SKILL_7_DOUBLE_SONIC_SLASH("Double Sonic Slash",5,7,"Duel"),
	SKILL_6_DOUBLE_SONIC_SLASH("Double Sonic Slash",5,6,"Earth Attack"),
	SKILL_3_DOUBLE_SONIC_SLASH("Double Sonic Slash",5,3,"Fire Attack"),
	SKILL_1_DOUBLE_SONIC_SLASH("Double Sonic Slash",5,1,"Power"),
	SKILL_4_DOUBLE_SONIC_SLASH("Double Sonic Slash",5,4,"Water Attack"),
	SKILL_5_DOUBLE_SONIC_SLASH("Double Sonic Slash",5,5,"Wind Attack"),
	SKILL_2_DRAIN_HEALTH("Drain Health",70,2,"Cost"),
	SKILL_1_DRAIN_HEALTH("Drain Health",70,1,"Power"),
	SKILL_3_DRAIN_HEALTH("Drain Health",70,3,"Sap"),
	SKILL_1_DREAMING_SPIRIT("Dreaming Spirit",1097,1,"Chance"),
	SKILL_2_DREAMING_SPIRIT("Dreaming Spirit",1097,2,"Cost"),
	SKILL_1_DRYAD_ROOT("Dryad Root",1201,1,"Chance"),
	SKILL_2_DRYAD_ROOT("Dryad Root",1201,2,"Cost"),
	SKILL_1_DUAL_WEAPON_MASTERY("Dual Weapon Mastery",144,1,"Power"),
	SKILL_2_DUAL_WEAPON_MASTERY("Dual Weapon Mastery",144,2,"Swiftness"),
	SKILL_1_DUELIST_SPIRIT("Duelist Spirit",297,1,"Power"),
	SKILL_1_EARTH_CHANT("Earth Chant",1391,1,"Cost"),
	SKILL_2_EARTH_CHANT("Earth Chant",1391,2,"Time"),
	SKILL_2_EARTHQUAKE("Earthquake",347,2,"Cost"),
	SKILL_3_EARTHQUAKE("Earthquake",347,3,"Earth Attack"),
	SKILL_1_EARTHQUAKE("Earthquake",347,1,"Power"),
	SKILL_2_ELEMENTAL_ASSAULT("Elemental Assault",1292,2,"Cost"),
	SKILL_3_ELEMENTAL_ASSAULT("Elemental Assault",1292,3,"Duel"),
	SKILL_1_ELEMENTAL_ASSAULT("Elemental Assault",1292,1,"Power"),
	SKILL_2_ELEMENTAL_HEAL("Elemental Heal",58,2,"Cost"),
	SKILL_3_ELEMENTAL_HEAL("Elemental Heal",58,3,"Cure Poison"),
	SKILL_4_ELEMENTAL_HEAL("Elemental Heal",58,4,"Heal Bleeding"),
	SKILL_1_ELEMENTAL_HEAL("Elemental Heal",58,1,"Power"),
	SKILL_2_ELEMENTAL_PROTECTION("Elemental Protection",1352,2,"Cost"),
	SKILL_1_ELEMENTAL_PROTECTION("Elemental Protection",1352,1,"Time"),
	SKILL_2_ELEMENTAL_STORM("Elemental Storm",1294,2,"Cost"),
	SKILL_3_ELEMENTAL_STORM("Elemental Storm",1294,3,"Duel"),
	SKILL_1_ELEMENTAL_STORM("Elemental Storm",1294,1,"Power"),
	SKILL_2_ELEMENTAL_SYMPHONY("Elemental Symphony",1293,2,"Cost"),
	SKILL_3_ELEMENTAL_SYMPHONY("Elemental Symphony",1293,3,"Duel"),
	SKILL_1_ELEMENTAL_SYMPHONY("Elemental Symphony",1293,1,"Power"),
	SKILL_2_EMPOWER("Empower",1059,2,"Cost"),
	SKILL_1_EMPOWER("Empower",1059,1,"Time"),
	SKILL_2_EMPOWERING_ECHO("Empowering Echo",1457,2,"Cost"),
	SKILL_1_EMPOWERING_ECHO("Empowering Echo",1457,1,"Time"),
	SKILL_2_ENERVATION("Enervation",1484,2,"Chance"),
	SKILL_1_ENERVATION("Enervation",1484,1,"Cost"),
	SKILL_1_ENTANGLE("Entangle",102,1,"Chance"),
	SKILL_3_ENTANGLE("Entangle",102,3,"Power"),
	SKILL_2_ENTANGLE("Entangle",102,2,"Time"),
	SKILL_2_ENUMA_ELISH("Enuma Elish",526,2,"Cost"),
	SKILL_4_ENUMA_ELISH("Enuma Elish",526,4,"Duel"),
	SKILL_3_ENUMA_ELISH("Enuma Elish",526,3,"Holy"),
	SKILL_1_ENUMA_ELISH("Enuma Elish",526,1,"Power"),
	SKILL_1_ERASE("Erase",1395,1,"Cost"),
	SKILL_3_EVADE_SHOT("Evade Shot",369,3,"Cost"),
	SKILL_8_EVADE_SHOT("Evade Shot",369,8,"Duel"),
	SKILL_7_EVADE_SHOT("Evade Shot",369,7,"Earth Attack"),
	SKILL_4_EVADE_SHOT("Evade Shot",369,4,"Fire Attack"),
	SKILL_1_EVADE_SHOT("Evade Shot",369,1,"Power"),
	SKILL_5_EVADE_SHOT("Evade Shot",369,5,"Water Attack"),
	SKILL_6_EVADE_SHOT("Evade Shot",369,6,"Wind Attack"),
	SKILL_1_EYE_OF_HUNTER("Eye of Hunter",359,1,"Power"),
	SKILL_2_EYE_OF_HUNTER("Eye of Hunter",359,2,"Time"),
	SKILL_2_EYE_OF_PAAGRIO("Eye of Pa\'agrio",1364,2,"Cost"),
	SKILL_1_EYE_OF_PAAGRIO("Eye of Pa\'agrio",1364,1,"Time"),
	SKILL_1_EYE_OF_SLAYER("Eye of Slayer",360,1,"Power"),
	SKILL_2_EYE_OF_SLAYER("Eye of Slayer",360,2,"Time"),
	SKILL_1_FAST_HP_RECOVERY("Fast HP Recovery",212,1,"Power"),
	SKILL_1_FAST_MANA_RECOVERY("Fast Mana Recovery",229,1,"Power"),
	SKILL_2_FAST_SHOT("Fast Shot",490,2,"Cost"),
	SKILL_1_FAST_SHOT("Fast Shot",490,1,"Time"),
	SKILL_1_FAST_SPELL_CASTING("Fast Spell Casting",228,1,"Power"),
	SKILL_2_FATAL_COUNTER("Fatal Counter",314,2,"Cost"),
	SKILL_7_FATAL_COUNTER("Fatal Counter",314,7,"Duel"),
	SKILL_6_FATAL_COUNTER("Fatal Counter",314,6,"Earth Attack"),
	SKILL_3_FATAL_COUNTER("Fatal Counter",314,3,"Fire Attack"),
	SKILL_1_FATAL_COUNTER("Fatal Counter",314,1,"Power"),
	SKILL_4_FATAL_COUNTER("Fatal Counter",314,4,"Water Attack"),
	SKILL_5_FATAL_COUNTER("Fatal Counter",314,5,"Wind Attack"),
	SKILL_2_FATAL_STRIKE("Fatal Strike",190,2,"Cost"),
	SKILL_6_FATAL_STRIKE("Fatal Strike",190,6,"Earth Attack"),
	SKILL_3_FATAL_STRIKE("Fatal Strike",190,3,"Fire Attack"),
	SKILL_1_FATAL_STRIKE("Fatal Strike",190,1,"Power"),
	SKILL_4_FATAL_STRIKE("Fatal Strike",190,4,"Water Attack"),
	SKILL_5_FATAL_STRIKE("Fatal Strike",190,5,"Wind Attack"),
	SKILL_1_FEAR("Fear",1092,1,"Chance"),
	SKILL_2_FEAR("Fear",1092,2,"Cost"),
	SKILL_1_FELL_SWOOP("Fell Swoop",421,1,"Power"),
	SKILL_2_FELL_SWOOP("Fell Swoop",421,2,"Time"),
	SKILL_2_FINAL_FORTRESS("Final Fortress",291,2,"Defense"),
	SKILL_1_FINAL_FORTRESS("Final Fortress",291,1,"Power"),
	SKILL_1_FINAL_FRENZY("Final Frenzy",290,1,"Power"),
	SKILL_2_FINAL_SERVITOR("Final Servitor",1349,2,"Cost"),
	SKILL_1_FINAL_SERVITOR("Final Servitor",1349,1,"Time"),
	SKILL_1_FIRE_TRAP("Fire Trap",514,1,"Power"),
	SKILL_2_FIRE_TRAP("Fire Trap",514,2,"Recycle"),
	SKILL_3_FIRE_VORTEX("Fire Vortex",1339,3,"Chance"),
	SKILL_2_FIRE_VORTEX("Fire Vortex",1339,2,"Cost"),
	SKILL_4_FIRE_VORTEX("Fire Vortex",1339,4,"Fire Attack"),
	SKILL_1_FIRE_VORTEX("Fire Vortex",1339,1,"Power"),
	SKILL_2_FIRE_VORTEX_BUSTER("Fire Vortex Buster",1451,2,"Cost"),
	SKILL_3_FIRE_VORTEX_BUSTER("Fire Vortex Buster",1451,3,"Fire Attack"),
	SKILL_1_FIRE_VORTEX_BUSTER("Fire Vortex Buster",1451,1,"Power"),
	SKILL_2_FIST_WEAPON_MASTERY("Fist Weapon Mastery",210,2,"Accuracy"),
	SKILL_1_FIST_WEAPON_MASTERY("Fist Weapon Mastery",210,1,"Power"),
	SKILL_2_FLAME_CHANT("Flame Chant",1002,2,"Cost"),
	SKILL_1_FLAME_CHANT("Flame Chant",1002,1,"Time"),
	SKILL_1_FLASH_TRAP("Flash Trap",517,1,"Power"),
	SKILL_2_FLASH_TRAP("Flash Trap",517,2,"Recycle"),
	SKILL_2_FOCUS("Focus",1077,2,"Cost"),
	SKILL_1_FOCUS("Focus",1077,1,"Time"),
	SKILL_1_FOCUS_CHANCE("Focus Chance",356,1,"Power"),
	SKILL_1_FOCUS_DEATH("Focus Death",355,1,"Power"),
	SKILL_1_FOCUS_MIND("Focus Mind",191,1,"Power"),
	SKILL_1_FOCUS_POWER("Focus Power",357,1,"Power"),
	SKILL_2_FORCE_BLASTER("Force Blaster",54,2,"Cost"),
	SKILL_7_FORCE_BLASTER("Force Blaster",54,7,"Duel"),
	SKILL_6_FORCE_BLASTER("Force Blaster",54,6,"Earth Attack"),
	SKILL_3_FORCE_BLASTER("Force Blaster",54,3,"Fire Attack"),
	SKILL_1_FORCE_BLASTER("Force Blaster",54,1,"Power"),
	SKILL_4_FORCE_BLASTER("Force Blaster",54,4,"Water Attack"),
	SKILL_5_FORCE_BLASTER("Force Blaster",54,5,"Wind Attack"),
	SKILL_2_FORCE_BURST("Force Burst",17,2,"Cost"),
	SKILL_7_FORCE_BURST("Force Burst",17,7,"Duel"),
	SKILL_6_FORCE_BURST("Force Burst",17,6,"Earth Attack"),
	SKILL_3_FORCE_BURST("Force Burst",17,3,"Fire Attack"),
	SKILL_1_FORCE_BURST("Force Burst",17,1,"Power"),
	SKILL_4_FORCE_BURST("Force Burst",17,4,"Water Attack"),
	SKILL_5_FORCE_BURST("Force Burst",17,5,"Wind Attack"),
	SKILL_2_FORCE_STORM("Force Storm",35,2,"Cost"),
	SKILL_7_FORCE_STORM("Force Storm",35,7,"Duel"),
	SKILL_6_FORCE_STORM("Force Storm",35,6,"Earth Attack"),
	SKILL_3_FORCE_STORM("Force Storm",35,3,"Fire Attack"),
	SKILL_1_FORCE_STORM("Force Storm",35,1,"Power"),
	SKILL_4_FORCE_STORM("Force Storm",35,4,"Water Attack"),
	SKILL_5_FORCE_STORM("Force Storm",35,5,"Wind Attack"),
	SKILL_1_FORTITUDE("Fortitude",335,1,"Power"),
	SKILL_3_FREEZING_SKIN("Freezing Skin",1238,3,"Defense"),
	SKILL_2_FREEZING_SKIN("Freezing Skin",1238,2,"Power"),
	SKILL_4_FREEZING_SKIN("Freezing Skin",1238,4,"ResistWater"),
	SKILL_1_FREEZING_SKIN("Freezing Skin",1238,1,"Time"),
	SKILL_3_FREEZING_STRIKE("Freezing Strike",105,3,"Chance"),
	SKILL_2_FREEZING_STRIKE("Freezing Strike",105,2,"Cost"),
	SKILL_1_FREEZING_STRIKE("Freezing Strike",105,1,"Power"),
	SKILL_4_FREEZING_STRIKE("Freezing Strike",105,4,"Water Attack"),
	SKILL_3_FROST_BOLT("Frost Bolt",1236,3,"Chance"),
	SKILL_2_FROST_BOLT("Frost Bolt",1236,2,"Cost"),
	SKILL_1_FROST_BOLT("Frost Bolt",1236,1,"Power"),
	SKILL_4_FROST_BOLT("Frost Bolt",1236,4,"Water Attack"),
	SKILL_2_FROST_WALL("Frost Wall",1174,2,"Cost"),
	SKILL_1_FROST_WALL("Frost Wall",1174,1,"Power"),
	SKILL_3_FROST_WALL("Frost Wall",1174,3,"Water Attack"),
	SKILL_2_GREATER_BATTLE_HEAL("Greater Battle Heal",1218,2,"Cost"),
	SKILL_1_GREATER_BATTLE_HEAL("Greater Battle Heal",1218,1,"Power"),
	SKILL_2_GREATER_GROUP_HEAL("Greater Group Heal",1219,2,"Cost"),
	SKILL_1_GREATER_GROUP_HEAL("Greater Group Heal",1219,1,"Power"),
	SKILL_2_GREATER_HEAL("Greater Heal",1217,2,"Cost"),
	SKILL_1_GREATER_HEAL("Greater Heal",1217,1,"Power"),
	SKILL_1_GREATER_MIGHT("Greater Might",1388,1,"Cost"),
	SKILL_2_GREATER_MIGHT("Greater Might",1388,2,"Time"),
	SKILL_1_GREATER_SHIELD("Greater Shield",1389,1,"Cost"),
	SKILL_2_GREATER_SHIELD("Greater Shield",1389,2,"Time"),
	SKILL_2_GUARD_STANCE("Guard Stance",288,2,"Cost"),
	SKILL_1_GUARD_STANCE("Guard Stance",288,1,"Power"),
	SKILL_2_GUIDANCE("Guidance",1240,2,"Cost"),
	SKILL_1_GUIDANCE("Guidance",1240,1,"Time"),
	SKILL_1_HAMMER_CRUSH("Hammer Crush",260,1,"Chance"),
	SKILL_2_HAMMER_CRUSH("Hammer Crush",260,2,"Cost"),
	SKILL_6_HAMMER_CRUSH("Hammer Crush",260,6,"Earth Attack"),
	SKILL_3_HAMMER_CRUSH("Hammer Crush",260,3,"Fire Attack"),
	SKILL_4_HAMMER_CRUSH("Hammer Crush",260,4,"Water Attack"),
	SKILL_5_HAMMER_CRUSH("Hammer Crush",260,5,"Wind Attack"),
	SKILL_1_HAMSTRING("Hamstring",127,1,"Chance"),
	SKILL_2_HAMSTRING("Hamstring",127,2,"Time"),
	SKILL_2_HAMSTRING_SHOT("Hamstring Shot",354,2,"Chance"),
	SKILL_1_HAMSTRING_SHOT("Hamstring Shot",354,1,"Power"),
	SKILL_2_HASTE("Haste",1086,2,"Cost"),
	SKILL_1_HASTE("Haste",1086,1,"Time"),
	SKILL_1_HAWK_EYE("Hawk Eye",131,1,"Time"),
	SKILL_1_HEALTH("Health",329,1,"Power"),
	SKILL_2_HEAVY_ARMOR_MASTERY("Heavy Armor Mastery",231,2,"Life"),
	SKILL_1_HEAVY_ARMOR_MASTERY("Heavy Armor Mastery",231,1,"Power"),
	SKILL_3_HEX("Hex",122,3,"Attack"),
	SKILL_1_HEX("Hex",122,1,"Chance"),
	SKILL_2_HEX("Hex",122,2,"Time"),
	SKILL_1_HIGHER_MANA_GAIN("Higher Mana Gain",285,1,"Power"),
	SKILL_3_HOLD_UNDEAD("Hold Undead",1042,3,"Attack"),
	SKILL_1_HOLD_UNDEAD("Hold Undead",1042,1,"Chance"),
	SKILL_2_HOLD_UNDEAD("Hold Undead",1042,2,"Cost"),
	SKILL_2_HOLY_WEAPON("Holy Weapon",1043,2,"Cost"),
	SKILL_1_HOLY_WEAPON("Holy Weapon",1043,1,"Time"),
	SKILL_1_HOWL("Howl",116,1,"Chance"),
	SKILL_2_HOWL("Howl",116,2,"Time"),
	SKILL_1_HURRICANE("Hurricane",1239,1,"Power"),
	SKILL_2_HURRICANE("Hurricane",1239,2,"Wind Attack"),
	SKILL_3_HURRICANE("Hurricane",1239,3,"Wind Vulnerability"),
	SKILL_2_HURRICANE_ASSAULT("Hurricane Assault",284,2,"Cost"),
	SKILL_7_HURRICANE_ASSAULT("Hurricane Assault",284,7,"Duel"),
	SKILL_6_HURRICANE_ASSAULT("Hurricane Assault",284,6,"Earth Attack"),
	SKILL_3_HURRICANE_ASSAULT("Hurricane Assault",284,3,"Fire Attack"),
	SKILL_1_HURRICANE_ASSAULT("Hurricane Assault",284,1,"Power"),
	SKILL_4_HURRICANE_ASSAULT("Hurricane Assault",284,4,"Water Attack"),
	SKILL_5_HURRICANE_ASSAULT("Hurricane Assault",284,5,"Wind Attack"),
	SKILL_2_HYDRO_BLAST("Hydro Blast",1235,2,"Cost"),
	SKILL_1_HYDRO_BLAST("Hydro Blast",1235,1,"Power"),
	SKILL_4_HYDRO_BLAST("Hydro Blast",1235,4,"Water Attack"),
	SKILL_3_HYDRO_BLAST("Hydro Blast",1235,3,"WaterVulnerability"),
	SKILL_3_ICE_DAGGER("Ice Dagger",1237,3,"Chance"),
	SKILL_2_ICE_DAGGER("Ice Dagger",1237,2,"Cost"),
	SKILL_1_ICE_DAGGER("Ice Dagger",1237,1,"Power"),
	SKILL_4_ICE_DAGGER("Ice Dagger",1237,4,"Water Attack"),
	SKILL_3_ICE_VORTEX("Ice Vortex",1340,3,"Chance"),
	SKILL_2_ICE_VORTEX("Ice Vortex",1340,2,"Cost"),
	SKILL_1_ICE_VORTEX("Ice Vortex",1340,1,"Power"),
	SKILL_4_ICE_VORTEX("Ice Vortex",1340,4,"Water Attack"),
	SKILL_2_ICE_VORTEX_CRUSHER("Ice Vortex Crusher",1453,2,"Cost"),
	SKILL_1_ICE_VORTEX_CRUSHER("Ice Vortex Crusher",1453,1,"Power"),
	SKILL_3_ICE_VORTEX_CRUSHER("Ice Vortex Crusher",1453,3,"Water Attack"),
	SKILL_2_INFERNO("Inferno",1289,2,"Cost"),
	SKILL_3_INFERNO("Inferno",1289,3,"Fire Attack"),
	SKILL_1_INFERNO("Inferno",1289,1,"Power"),
	SKILL_1_INNER_RHYTHM("Inner Rhythm",428,1,"Power"),
	SKILL_2_INVIGOR("Invigor",1032,2,"Cost"),
	SKILL_3_INVIGOR("Invigor",1032,3,"Power"),
	SKILL_1_INVIGOR("Invigor",1032,1,"Time"),
	SKILL_2_IRON_WILL("Iron Will",72,2,"Cost"),
	SKILL_1_IRON_WILL("Iron Will",72,1,"Time"),
	SKILL_2_JUDGMENT("Judgment",401,2,"Cost"),
	SKILL_4_JUDGMENT("Judgment",401,4,"Dark Attack"),
	SKILL_3_JUDGMENT("Judgment",401,3,"Modify Critical"),
	SKILL_1_JUDGMENT("Judgment",401,1,"Power"),
	SKILL_2_KISS_OF_EVA("Kiss of Eva",1073,2,"Cost"),
	SKILL_1_KISS_OF_EVA("Kiss of Eva",1073,1,"Time"),
	SKILL_1_KNIGHTHOOD("Knighthood",429,1,"Power"),
	SKILL_2_LEOPOLD("Leopold",1469,2,"Cost"),
	SKILL_4_LEOPOLD("Leopold",1469,4,"Duel"),
	SKILL_3_LEOPOLD("Leopold",1469,3,"Fire Attack"),
	SKILL_1_LEOPOLD("Leopold",1469,1,"Power"),
	SKILL_7_LETHAL_BLOW("Lethal Blow",344,7,"Duel"),
	SKILL_6_LETHAL_BLOW("Lethal Blow",344,6,"Earth Attack"),
	SKILL_3_LETHAL_BLOW("Lethal Blow",344,3,"Fire Attack"),
	SKILL_1_LETHAL_BLOW("Lethal Blow",344,1,"Power"),
	SKILL_4_LETHAL_BLOW("Lethal Blow",344,4,"Water Attack"),
	SKILL_5_LETHAL_BLOW("Lethal Blow",344,5,"Wind Attack"),
	SKILL_2_LETHAL_SHOT("Lethal Shot",343,2,"Cost"),
	SKILL_7_LETHAL_SHOT("Lethal Shot",343,7,"Duel"),
	SKILL_6_LETHAL_SHOT("Lethal Shot",343,6,"Earth Attack"),
	SKILL_3_LETHAL_SHOT("Lethal Shot",343,3,"Fire Attack"),
	SKILL_1_LETHAL_SHOT("Lethal Shot",343,1,"Power"),
	SKILL_4_LETHAL_SHOT("Lethal Shot",343,4,"Water Attack"),
	SKILL_5_LETHAL_SHOT("Lethal Shot",343,5,"Wind Attack"),
	SKILL_2_LIFE_LEECH("Life Leech",289,2,"Cost"),
	SKILL_1_LIFE_LEECH("Life Leech",289,1,"Power"),
	SKILL_3_LIFE_LEECH("Life Leech",289,3,"Sap"),
	SKILL_2_LIFE_SCAVENGE("Life Scavenge",46,2,"Cost"),
	SKILL_1_LIFE_SCAVENGE("Life Scavenge",46,1,"Power"),
	SKILL_2_LIFE_TO_SOUL("Life to Soul",502,2,"Cost"),
	SKILL_1_LIFE_TO_SOUL("Life to Soul",502,1,"Power"),
	SKILL_2_LIGHT_ARMOR_MASTERY("Light Armor Mastery",227,2,"Life"),
	SKILL_1_LIGHT_ARMOR_MASTERY("Light Armor Mastery",227,1,"Power"),
	SKILL_3_LIGHT_VORTEX("Light Vortex",1342,3,"Chance"),
	SKILL_2_LIGHT_VORTEX("Light Vortex",1342,2,"Cost"),
	SKILL_4_LIGHT_VORTEX("Light Vortex",1342,4,"Holy Attack"),
	SKILL_1_LIGHT_VORTEX("Light Vortex",1342,1,"Power"),
	SKILL_3_LIGHTNING_BARRIER("Lightning Barrier",1515,3,"Chance"),
	SKILL_2_LIGHTNING_BARRIER("Lightning Barrier",1515,2,"Cost"),
	SKILL_1_LIGHTNING_BARRIER("Lightning Barrier",1515,1,"Power"),
	SKILL_3_LIGHTNING_STRIKE("Lightning Strike",279,3,"Chance"),
	SKILL_2_LIGHTNING_STRIKE("Lightning Strike",279,2,"Cost"),
	SKILL_1_LIGHTNING_STRIKE("Lightning Strike",279,1,"Power"),
	SKILL_1_LURE("Lure",51,1,"Cost"),
	SKILL_2_MAGIC_BARRIER("Magic Barrier",1036,2,"Cost"),
	SKILL_1_MAGIC_BARRIER("Magic Barrier",1036,1,"Time"),
	SKILL_1_MAGIC_IMMUNITY("Magic Immunity",466,1,"Power"),
	SKILL_1_MAGIC_IMPULSE("Magic Impulse",1479,1,"Cost"),
	SKILL_3_MAGIC_IMPULSE("Magic Impulse",1479,3,"Recycle"),
	SKILL_2_MAGIC_IMPULSE("Magic Impulse",1479,2,"Time"),
	SKILL_2_MAGICAL_BACKFIRE("Magical BackFire",1396,2,"Chance"),
	SKILL_1_MAGICAL_BACKFIRE("Magical BackFire",1396,1,"Cost"),
	SKILL_3_MAGICAL_BACKFIRE("Magical BackFire",1396,3,"Mana"),
	SKILL_2_MAGNUS_CHANT("Magnus Chant",1413,2,"Cost"),
	SKILL_1_MAGNUS_CHANT("Magnus Chant",1413,1,"Time"),
	SKILL_1_MAJESTY("Majesty",82,1,"Power"),
	SKILL_2_MAJESTY("Majesty",82,2,"Time"),
	SKILL_2_MAJOR_GROUP_HEAL("Major Group Heal",1402,2,"Cost"),
	SKILL_3_MAJOR_GROUP_HEAL("Major Group Heal",1402,3,"Cure Poison"),
	SKILL_4_MAJOR_GROUP_HEAL("Major Group Heal",1402,4,"Heal Bleeding"),
	SKILL_1_MAJOR_GROUP_HEAL("Major Group Heal",1402,1,"Power"),
	SKILL_2_MAJOR_HEAL("Major Heal",1401,2,"Cost"),
	SKILL_1_MAJOR_HEAL("Major Heal",1401,1,"Power"),
	SKILL_2_MANA_BURN("Mana Burn",1398,2,"Cost"),
	SKILL_1_MANA_BURN("Mana Burn",1398,1,"Power"),
	SKILL_2_MANA_GAIN("Mana Gain",1460,2,"Cost"),
	SKILL_1_MANA_GAIN("Mana Gain",1460,1,"Time"),
	SKILL_1_MANA_PUMP("Mana Pump",1565,1,"Power"),
	SKILL_1_MANA_REGENERATION("Mana Regeneration",1047,1,"Power"),
	SKILL_2_MANA_REGENERATION("Mana Regeneration",1047,2,"Time"),
	SKILL_2_MANA_STORM("Mana Storm",1399,2,"Cost"),
	SKILL_1_MANA_STORM("Mana Storm",1399,1,"Power"),
	SKILL_1_MASS_BLOCK_SHIELD("Mass Block Shield",1360,1,"Chance"),
	SKILL_2_MASS_BLOCK_SHIELD("Mass Block Shield",1360,2,"Cost"),
	SKILL_1_MASS_BLOCK_WIND_WALK("Mass Block Wind Walk",1361,1,"Chance"),
	SKILL_2_MASS_BLOCK_WIND_WALK("Mass Block Wind Walk",1361,2,"Cost"),
	SKILL_1_MASS_DISARM("Mass Disarm",794,1,"Chance"),
	SKILL_2_MASS_DISARM("Mass Disarm",794,2,"Recycle"),
	SKILL_2_MASS_FEAR("Mass Fear",1381,2,"Chance"),
	SKILL_1_MASS_FEAR("Mass Fear",1381,1,"Cost"),
	SKILL_2_MASS_GLOOM("Mass Gloom",1382,2,"Chance"),
	SKILL_1_MASS_GLOOM("Mass Gloom",1382,1,"Cost"),
	SKILL_2_MASS_RESURRECTION("Mass Resurrection",1254,2,"Cost"),
	SKILL_1_MASS_RESURRECTION("Mass Resurrection",1254,1,"Power"),
	SKILL_2_MASS_SHACKLING("Mass Shackling",404,2,"Chance"),
	SKILL_1_MASS_SHACKLING("Mass Shackling",404,1,"Power"),
	SKILL_1_MASS_SLOW("Mass Slow",1298,1,"Chance"),
	SKILL_2_MASS_SLOW("Mass Slow",1298,2,"Cost"),
	SKILL_1_MASS_SUMMON_AQUA_CUBIC("Mass Summon Aqua Cubic",1329,1,"Power"),
	SKILL_1_MASS_SUMMON_PHANTOM_CUBIC("Mass Summon Phantom Cubic",1330,1,"Power"),
	SKILL_1_MASS_SUMMON_STORM_CUBIC("Mass Summon Storm Cubic",1328,1,"Power"),
	SKILL_3_MASS_SURRENDER_TO_FIRE("Mass Surrender to Fire",1383,3,"Chance"),
	SKILL_2_MASS_SURRENDER_TO_FIRE("Mass Surrender to Fire",1383,2,"Cost"),
	SKILL_1_MASS_SURRENDER_TO_FIRE("Mass Surrender to Fire",1383,1,"Power"),
	SKILL_3_MASS_SURRENDER_TO_WATER("Mass Surrender to Water",1384,3,"Chance"),
	SKILL_2_MASS_SURRENDER_TO_WATER("Mass Surrender to Water",1384,2,"Cost"),
	SKILL_1_MASS_SURRENDER_TO_WATER("Mass Surrender to Water",1384,1,"Power"),
	SKILL_3_MASS_SURRENDER_TO_WIND("Mass Surrender to Wind",1385,3,"Chance"),
	SKILL_2_MASS_SURRENDER_TO_WIND("Mass Surrender to Wind",1385,2,"Cost"),
	SKILL_1_MASS_SURRENDER_TO_WIND("Mass Surrender to Wind",1385,1,"Power"),
	SKILL_1_MASTER_OF_COMBAT("Master of Combat",430,1,"Power"),
	SKILL_2_MENTAL_IMPOVERISH("Mental Impoverish",1486,2,"Chance"),
	SKILL_1_MENTAL_IMPOVERISH("Mental Impoverish",1486,1,"Cost"),
	SKILL_2_MENTAL_SHIELD("Mental Shield",1035,2,"Cost"),
	SKILL_1_MENTAL_SHIELD("Mental Shield",1035,1,"Time"),
	SKILL_2_MIGHT("Might",1068,2,"Cost"),
	SKILL_1_MIGHT("Might",1068,1,"Time"),
	SKILL_2_MIGHT_OF_HEAVEN("Might of Heaven",1028,2,"Cost"),
	SKILL_3_MIGHT_OF_HEAVEN("Might of Heaven",1028,3,"Holy Attack"),
	SKILL_1_MIGHT_OF_HEAVEN("Might of Heaven",1028,1,"Power"),
	SKILL_2_MIGHTY_SERVITOR("Mighty Servitor",1146,2,"Cost"),
	SKILL_1_MIGHTY_SERVITOR("Mighty Servitor",1146,1,"Time"),
	SKILL_1_MORTAL_STRIKE("Mortal Strike",410,1,"Chance"),
	SKILL_2_MORTAL_STRIKE("Mortal Strike",410,2,"Time"),
	SKILL_1_NECROMANCY("Necromancy",434,1,"Power"),
	SKILL_2_OBLIVION("Oblivion",1481,2,"Chance"),
	SKILL_1_OBLIVION("Oblivion",1481,1,"Cost"),
	SKILL_2_PAAGRIAN_GIFT("Pa agrian Gift",1003,2,"Cost"),
	SKILL_1_PAAGRIAN_GIFT("Pa agrian Gift",1003,1,"Time"),
	SKILL_2_PAAGRIAN_HASTE("Pa agrian Haste",1282,2,"Cost"),
	SKILL_1_PAAGRIAN_HASTE("Pa agrian Haste",1282,1,"Time"),
	SKILL_2_PAAGRIOS_EMBLEM("Pa agrios Emblem",1415,2,"Cost"),
	SKILL_1_PAAGRIOS_EMBLEM("Pa agrios Emblem",1415,1,"Time"),
	SKILL_2_PAAGRIOS_FIST("Pa agrios Fist",1416,2,"Cost"),
	SKILL_1_PAAGRIOS_FIST("Pa agrios Fist",1416,1,"Power"),
	SKILL_1_PAIN_OF_SAGITTARIUS("Pain of Sagittarius",417,1,"Power"),
	SKILL_1_PARRY_STANCE("Parry Stance",339,1,"Power"),
	SKILL_1_POISON_BLADE_DANCE("Poison Blade Dance",84,1,"Chance"),
	SKILL_2_POISON_BLADE_DANCE("Poison Blade Dance",84,2,"Time"),
	SKILL_1_POISON_TRAP("Poison Trap",515,1,"Power"),
	SKILL_2_POISON_TRAP("Poison Trap",515,2,"Recycle"),
	SKILL_3_POISONOUS_CLOUD("Poisonous Cloud",1167,3,"Chance"),
	SKILL_2_POISONOUS_CLOUD("Poisonous Cloud",1167,2,"Cost"),
	SKILL_1_POISONOUS_CLOUD("Poisonous Cloud",1167,1,"Power"),
	SKILL_2_POLEARM_ACCURACY("Polearm Accuracy",422,2,"Cost"),
	SKILL_1_POLEARM_ACCURACY("Polearm Accuracy",422,1,"Power"),
	SKILL_1_POLEARM_MASTERY("Polearm Mastery",216,1,"Power"),
	SKILL_3_POWER_BREAK("Power Break",115,3,"Attack"),
	SKILL_1_POWER_BREAK("Power Break",115,1,"Chance"),
	SKILL_2_POWER_BREAK("Power Break",115,2,"Time"),
	SKILL_2_PRAHNAH("Prahnah",1470,2,"Cost"),
	SKILL_1_PRAHNAH("Prahnah",1470,1,"Power"),
	SKILL_4_PRAHNAH("Prahnah",1470,4,"Recycle"),
	SKILL_3_PRAHNAH("Prahnah",1470,3,"Time"),
	SKILL_2_PRAYER("Prayer",1307,2,"Cost"),
	SKILL_1_PRAYER("Prayer",1307,1,"Time"),
	SKILL_1_PRIDE_OF_KAMAEL("Pride of Kamael",1444,1,"Power"),
	SKILL_4_PRIDE_OF_KAMAEL("Pride of Kamael",1444,4,"Time"),
	SKILL_2_PROMINENCE("Prominence",1230,2,"Cost"),
	SKILL_4_PROMINENCE("Prominence",1230,4,"Fire Attack"),
	SKILL_3_PROMINENCE("Prominence",1230,3,"FireVulnerability"),
	SKILL_1_PROMINENCE("Prominence",1230,1,"Power"),
	SKILL_2_PROPHECY_OF_FIRE("Prophecy of Fire",1356,2,"Cost"),
	SKILL_3_PROPHECY_OF_FIRE("Prophecy of Fire",1356,3,"Decrease Penalty"),
	SKILL_1_PROPHECY_OF_FIRE("Prophecy of Fire",1356,1,"Time"),
	SKILL_2_PROPHECY_OF_WATER("Prophecy of Water",1355,2,"Cost"),
	SKILL_3_PROPHECY_OF_WATER("Prophecy of Water",1355,3,"Decrease Penalty"),
	SKILL_1_PROPHECY_OF_WATER("Prophecy of Water",1355,1,"Time"),
	SKILL_2_PROPHECY_OF_WIND("Prophecy of Wind",1357,2,"Cost"),
	SKILL_3_PROPHECY_OF_WIND("Prophecy of Wind",1357,3,"Decrease Penalty"),
	SKILL_1_PROPHECY_OF_WIND("Prophecy of Wind",1357,1,"Time"),
	SKILL_1_PROTECTION_FROM_DARKNESS("Protection from Darkness",1442,1,"Power"),
	SKILL_2_PROTECTION_FROM_DARKNESS("Protection from Darkness",1442,2,"Time"),
	SKILL_1_PROTECTION_INSTINCT("Protection Instinct",1478,1,"Cost"),
	SKILL_3_PROTECTION_INSTINCT("Protection Instinct",1478,3,"Recycle"),
	SKILL_2_PROTECTION_INSTINCT("Protection Instinct",1478,2,"Time"),
	SKILL_2_PUNCH_OF_DOOM("Punch of Doom",81,2,"Cost"),
	SKILL_3_PUNCH_OF_DOOM("Punch of Doom",81,3,"Fire Attack"),
	SKILL_1_PUNCH_OF_DOOM("Punch of Doom",81,1,"Power"),
	SKILL_1_QUICK_STEP("Quick Step",169,1,"Power"),
	SKILL_1_RAGE("Rage",94,1,"Power"),
	SKILL_2_RAGE_OF_PAAGRIO("Rage of Pa agrio",1261,2,"Cost"),
	SKILL_1_RAGE_OF_PAAGRIO("Rage of Pa agrio",1261,1,"Time"),
	SKILL_2_RAIN_OF_FIRE("Rain of Fire",1296,2,"Cost"),
	SKILL_3_RAIN_OF_FIRE("Rain of Fire",1296,3,"Fire Attack"),
	SKILL_1_RAIN_OF_FIRE("Rain of Fire",1296,1,"Power"),
	SKILL_1_RAPID_FIRE("Rapid Fire",413,1,"Power"),
	SKILL_2_RAPID_FIRE("Rapid Fire",413,2,"Time"),
	SKILL_2_RAPID_SHOT("Rapid Shot",99,2,"Cost"),
	SKILL_1_RAPID_SHOT("Rapid Shot",99,1,"Time"),
	SKILL_1_RAPIER_MASTERY("Rapier Mastery",474,1,"Power"),
	SKILL_2_RAPIER_MASTERY("Rapier Mastery",474,2,"Swiftness"),
	SKILL_2_REAL_TARGET("Real Target",522,2,"DecreaseAttack"),
	SKILL_1_REAL_TARGET("Real Target",522,1,"DecreaseDefense"),
	SKILL_4_REAL_TARGET("Real Target",522,4,"DecreaseMagicAttack"),
	SKILL_3_REAL_TARGET("Real Target",522,3,"DecreaseMagic Defense"),
	SKILL_2_RECHARGE("Recharge",1013,2,"Cost"),
	SKILL_1_RECHARGE("Recharge",1013,1,"Power"),
	SKILL_2_REFLECT_DAMAGE("Reflect Damage",86,2,"Cost"),
	SKILL_1_REFLECT_DAMAGE("Reflect Damage",86,1,"Time"),
	SKILL_2_REGENERATION("Regeneration",1044,2,"Cost"),
	SKILL_1_REGENERATION("Regeneration",1044,1,"Time"),
	SKILL_2_REPOSE("Repose",1034,2,"Cost"),
	SKILL_1_REPOSE("Repose",1034,1,"Power"),
	SKILL_2_RESIST_AQUA("Resist Aqua",1182,2,"Cost"),
	SKILL_3_RESIST_AQUA("Resist Aqua",1182,3,"Power"),
	SKILL_1_RESIST_AQUA("Resist Aqua",1182,1,"Time"),
	SKILL_2_RESIST_DARK("Resist Dark",1393,2,"Cost"),
	SKILL_1_RESIST_DARK("Resist Dark",1393,1,"Power"),
	SKILL_3_RESIST_DARK("Resist Dark",1393,3,"Time"),
	SKILL_2_RESIST_EARTH("Resist Earth",1548,2,"Cost"),
	SKILL_3_RESIST_EARTH("Resist Earth",1548,3,"Power"),
	SKILL_1_RESIST_EARTH("Resist Earth",1548,1,"Time"),
	SKILL_2_RESIST_FIRE("Resist Fire",1191,2,"Cost"),
	SKILL_3_RESIST_FIRE("Resist Fire",1191,3,"Power"),
	SKILL_1_RESIST_FIRE("Resist Fire",1191,1,"Time"),
	SKILL_2_RESIST_HOLY("Resist Holy",1392,2,"Cost"),
	SKILL_1_RESIST_HOLY("Resist Holy",1392,1,"Power"),
	SKILL_3_RESIST_HOLY("Resist Holy",1392,3,"Time"),
	SKILL_2_RESIST_POISON("Resist Poison",1033,2,"Cost"),
	SKILL_3_RESIST_POISON("Resist Poison",1033,3,"Power"),
	SKILL_1_RESIST_POISON("Resist Poison",1033,1,"Time"),
	SKILL_2_RESIST_SHOCK("Resist Shock",1259,2,"Cost"),
	SKILL_3_RESIST_SHOCK("Resist Shock",1259,3,"Power"),
	SKILL_1_RESIST_SHOCK("Resist Shock",1259,1,"Time"),
	SKILL_2_RESIST_WIND("Resist Wind",1189,2,"Cost"),
	SKILL_3_RESIST_WIND("Resist Wind",1189,3,"Power"),
	SKILL_1_RESIST_WIND("Resist Wind",1189,1,"Time"),
	SKILL_2_RESTORATION("Restoration",1487,2,"Cost"),
	SKILL_1_RESTORATION("Restoration",1487,1,"Power"),
	SKILL_1_RESTORATION_IMPACT("Restoration Impact",1488,1,"Power"),
	SKILL_2_RESTORE_LIFE("Restore Life",1258,2,"Cost"),
	SKILL_1_RESTORE_LIFE("Restore Life",1258,1,"Power"),
	SKILL_2_RISING_SHOT("Rising Shot",508,2,"Cost"),
	SKILL_7_RISING_SHOT("Rising Shot",508,7,"Duel"),
	SKILL_6_RISING_SHOT("Rising Shot",508,6,"Earth Attack"),
	SKILL_3_RISING_SHOT("Rising Shot",508,3,"Fire Attack"),
	SKILL_1_RISING_SHOT("Rising Shot",508,1,"Power"),
	SKILL_4_RISING_SHOT("Rising Shot",508,4,"Water Attack"),
	SKILL_5_RISING_SHOT("Rising Shot",508,5,"Wind Attack"),
	SKILL_2_RITUAL_OF_LIFE("Ritual of Life",1306,2,"Cost"),
	SKILL_1_RITUAL_OF_LIFE("Ritual of Life",1306,1,"Power"),
	SKILL_3_ROBE_MASTERY("Robe Mastery",234,3,"Magic Defense"),
	SKILL_2_ROBE_MASTERY("Robe Mastery",234,2,"Mana"),
	SKILL_1_ROBE_MASTERY("Robe Mastery",234,1,"Power"),
	SKILL_3_RUSH_IMPACT("Rush Impact",793,3,"Chance"),
	SKILL_2_RUSH_IMPACT("Rush Impact",793,2,"Cost"),
	SKILL_8_RUSH_IMPACT("Rush Impact",793,8,"Duel"),
	SKILL_7_RUSH_IMPACT("Rush Impact",793,7,"Earth Attack"),
	SKILL_4_RUSH_IMPACT("Rush Impact",793,4,"Fire Attack"),
	SKILL_1_RUSH_IMPACT("Rush Impact",793,1,"Power"),
	SKILL_5_RUSH_IMPACT("Rush Impact",793,5,"Water Attack"),
	SKILL_6_RUSH_IMPACT("Rush Impact",793,6,"Wind Attack"),
	SKILL_2_SACRIFICE("Sacrifice",69,2,"Cost"),
	SKILL_3_SACRIFICE("Sacrifice",69,3,"Cure Poison"),
	SKILL_4_SACRIFICE("Sacrifice",69,4,"Heal Bleeding"),
	SKILL_1_SACRIFICE("Sacrifice",69,1,"Power"),
	SKILL_3_SANCTUARY("Sanctuary",97,3,"Attack"),
	SKILL_1_SANCTUARY("Sanctuary",97,1,"Chance"),
	SKILL_2_SANCTUARY("Sanctuary",97,2,"Cost"),
	SKILL_4_SANCTUARY("Sanctuary",97,4,"Modify Critical"),
	SKILL_2_SAND_BOMB("Sand Bomb",412,2,"Chance"),
	SKILL_1_SAND_BOMB("Sand Bomb",412,1,"Cost"),
	SKILL_1_SEAL_OF_BINDING("Seal of Binding",1208,1,"Chance"),
	SKILL_2_SEAL_OF_BINDING("Seal of Binding",1208,2,"Cost"),
	SKILL_1_SEAL_OF_BLOCKADE("Seal of Blockade",1462,1,"Chance"),
	SKILL_2_SEAL_OF_BLOCKADE("Seal of Blockade",1462,2,"Cost"),
	SKILL_1_SEAL_OF_CHAOS("Seal of Chaos",1096,1,"Chance"),
	SKILL_2_SEAL_OF_CHAOS("Seal of Chaos",1096,2,"Cost"),
	SKILL_1_SEAL_OF_DESPAIR("Seal of Despair",1366,1,"Chance"),
	SKILL_2_SEAL_OF_DESPAIR("Seal of Despair",1366,2,"Cost"),
	SKILL_1_SEAL_OF_DISEASE("Seal of Disease",1367,1,"Chance"),
	SKILL_2_SEAL_OF_DISEASE("Seal of Disease",1367,2,"Cost"),
	SKILL_1_SEAL_OF_SCOURGE("Seal of Scourge",1247,1,"Chance"),
	SKILL_2_SEAL_OF_SCOURGE("Seal of Scourge",1247,2,"Cost"),
	SKILL_1_SEAL_OF_SILENCE("Seal of Silence",1246,1,"Chance"),
	SKILL_2_SEAL_OF_SILENCE("Seal of Silence",1246,2,"Cost"),
	SKILL_1_SEAL_OF_SLOW("Seal of Slow",1099,1,"Chance"),
	SKILL_2_SEAL_OF_SLOW("Seal of Slow",1099,2,"Cost"),
	SKILL_1_SEAL_OF_SUSPENSION("Seal of Suspension",1248,1,"Chance"),
	SKILL_2_SEAL_OF_SUSPENSION("Seal of Suspension",1248,2,"Cost"),
	SKILL_1_SEAL_OF_WINTER("Seal of Winter",1104,1,"Chance"),
	SKILL_2_SEAL_OF_WINTER("Seal of Winter",1104,2,"Cost"),
	SKILL_2_SERVITOR_EMPOWERMENT("Servitor Empowerment",1299,2,"Recycle"),
	SKILL_1_SERVITOR_EMPOWERMENT("Servitor Empowerment",1299,1,"Time"),
	SKILL_2_SERVITOR_HASTE("Servitor Haste",1141,2,"Cost"),
	SKILL_1_SERVITOR_HASTE("Servitor Haste",1141,1,"Time"),
	SKILL_2_SERVITOR_HEAL("Servitor Heal",1127,2,"Cost"),
	SKILL_1_SERVITOR_HEAL("Servitor Heal",1127,1,"Power"),
	SKILL_2_SERVITOR_MAGIC_SHIELD("Servitor Magic Shield",1139,2,"Cost"),
	SKILL_1_SERVITOR_MAGIC_SHIELD("Servitor Magic Shield",1139,1,"Time"),
	SKILL_2_SERVITOR_PHYSICAL_SHIELD("Servitor Physical Shield",1140,2,"Cost"),
	SKILL_1_SERVITOR_PHYSICAL_SHIELD("Servitor Physical Shield",1140,1,"Time"),
	SKILL_2_SERVITOR_RECHARGE("Servitor Recharge",1126,2,"Cost"),
	SKILL_1_SERVITOR_RECHARGE("Servitor Recharge",1126,1,"Power"),
	SKILL_2_SERVITOR_WIND_WALK("Servitor Wind Walk",1144,2,"Cost"),
	SKILL_1_SERVITOR_WIND_WALK("Servitor Wind Walk",1144,1,"Time"),
	SKILL_2_SHACKLE("Shackle",403,2,"Chance"),
	SKILL_1_SHACKLE("Shackle",403,1,"Power"),
	SKILL_1_SHADOW_BIND("Shadow Bind",1446,1,"Chance"),
	SKILL_2_SHADOW_BIND("Shadow Bind",1446,2,"Time"),
	SKILL_2_SHADOW_FLARE("Shadow Flare",1267,2,"Cost"),
	SKILL_3_SHADOW_FLARE("Shadow Flare",1267,3,"Dark Attack"),
	SKILL_1_SHADOW_FLARE("Shadow Flare",1267,1,"Power"),
	SKILL_1_SHARPSHOOTING("Sharpshooting",521,1,"Power"),
	SKILL_2_SHARPSHOOTING("Sharpshooting",521,2,"Time"),
	SKILL_2_SHIELD("Shield",1040,2,"Cost"),
	SKILL_1_SHIELD("Shield",1040,1,"Time"),
	SKILL_1_SHIELD_BASH("Shield Bash",352,1,"Chance"),
	SKILL_5_SHIELD_BASH("Shield Bash",352,5,"Weaken Earth"),
	SKILL_2_SHIELD_BASH("Shield Bash",352,2,"Weaken Fire"),
	SKILL_3_SHIELD_BASH("Shield Bash",352,3,"Weaken Water"),
	SKILL_4_SHIELD_BASH("Shield Bash",352,4,"Weaken Wind"),
	SKILL_2_SHIELD_FORTRESS("Shield Fortress",322,2,"Cost"),
	SKILL_1_SHIELD_FORTRESS("Shield Fortress",322,1,"Power"),
	SKILL_1_SHIELD_MASTERY("Shield Mastery",153,1,"Defense"),
	SKILL_1_SHIELD_OF_FAITH("Shield of Faith",528,1,"Power"),
	SKILL_3_SHIELD_OF_FAITH("Shield of Faith",528,3,"Recycle"),
	SKILL_2_SHIELD_OF_FAITH("Shield of Faith",528,2,"Time"),
	SKILL_2_SHIELD_OF_PAAGRIO("Shield of Pa agrio",1250,2,"Cost"),
	SKILL_1_SHIELD_OF_PAAGRIO("Shield of Pa agrio",1250,1,"Time"),
	SKILL_1_SHIELD_SLAM("Shield Slam",353,1,"Chance"),
	SKILL_3_SHIELD_SLAM("Shield Slam",353,3,"Weaken Dark"),
	SKILL_2_SHIELD_SLAM("Shield Slam",353,2,"Weaken Holy"),
	SKILL_1_SHIELD_STUN("Shield Stun",92,1,"Recycle"),
	SKILL_2_SHIELD_STUN("Shield Stun",92,2,"Time"),
	SKILL_6_SHIELD_STUN("Shield Stun",92,6,"Weaken Earth"),
	SKILL_3_SHIELD_STUN("Shield Stun",92,3,"Weaken Fire"),
	SKILL_4_SHIELD_STUN("Shield Stun",92,4,"Weaken Water"),
	SKILL_5_SHIELD_STUN("Shield Stun",92,5,"Weaken Wind"),
	SKILL_2_SHINING_EDGE("Shining Edge",505,2,"Cost"),
	SKILL_7_SHINING_EDGE("Shining Edge",505,7,"Duel"),
	SKILL_6_SHINING_EDGE("Shining Edge",505,6,"Earth Attack"),
	SKILL_3_SHINING_EDGE("Shining Edge",505,3,"Fire Attack"),
	SKILL_1_SHINING_EDGE("Shining Edge",505,1,"Power"),
	SKILL_4_SHINING_EDGE("Shining Edge",505,4,"Water Attack"),
	SKILL_5_SHINING_EDGE("Shining Edge",505,5,"Wind Attack"),
	SKILL_3_SHOCK_BLAST("Shock Blast",361,3,"Chance"),
	SKILL_2_SHOCK_BLAST("Shock Blast",361,2,"Cost"),
	SKILL_1_SHOCK_BLAST("Shock Blast",361,1,"Power"),
	SKILL_1_SHOCK_STOMP("Shock Stomp",452,1,"Chance"),
	SKILL_2_SHOULDER_CHARGE("Shoulder Charge",494,2,"Chance"),
	SKILL_7_SHOULDER_CHARGE("Shoulder Charge",494,7,"Duel"),
	SKILL_6_SHOULDER_CHARGE("Shoulder Charge",494,6,"Earth Attack"),
	SKILL_3_SHOULDER_CHARGE("Shoulder Charge",494,3,"Fire Attack"),
	SKILL_1_SHOULDER_CHARGE("Shoulder Charge",494,1,"Power"),
	SKILL_4_SHOULDER_CHARGE("Shoulder Charge",494,4,"Water Attack"),
	SKILL_5_SHOULDER_CHARGE("Shoulder Charge",494,5,"Wind Attack"),
	SKILL_1_SILENCE("Silence",1064,1,"Chance"),
	SKILL_2_SILENCE("Silence",1064,2,"Cost"),
	SKILL_1_SILENT_MOVE("Silent Move",221,1,"Decrease Penalty"),
	SKILL_2_SLASHING_BLADE("Slashing Blade",496,2,"Cost"),
	SKILL_7_SLASHING_BLADE("Slashing Blade",496,7,"Duel"),
	SKILL_6_SLASHING_BLADE("Slashing Blade",496,6,"Earth Attack"),
	SKILL_3_SLASHING_BLADE("Slashing Blade",496,3,"Fire Attack"),
	SKILL_1_SLASHING_BLADE("Slashing Blade",496,1,"Power"),
	SKILL_4_SLASHING_BLADE("Slashing Blade",496,4,"Water Attack"),
	SKILL_5_SLASHING_BLADE("Slashing Blade",496,5,"Wind Attack"),
	SKILL_1_SLEEP("Sleep",1069,1,"Chance"),
	SKILL_2_SLEEP("Sleep",1069,2,"Cost"),
	SKILL_1_SLEEPING_CLOUD("Sleeping Cloud",1072,1,"Chance"),
	SKILL_2_SLEEPING_CLOUD("Sleeping Cloud",1072,2,"Cost"),
	SKILL_1_SLOW("Slow",1160,1,"Chance"),
	SKILL_2_SLOW("Slow",1160,2,"Cost"),
	SKILL_3_SLOW("Slow",1160,3,"Defense"),
	SKILL_1_SLOW_TRAP("Slow Trap",516,1,"Power"),
	SKILL_2_SLOW_TRAP("Slow Trap",516,2,"Recycle"),
	SKILL_2_SNIPE("Snipe",313,2,"Cost"),
	SKILL_1_SNIPE("Snipe",313,1,"Power"),
	SKILL_2_SOLAR_FLARE("Solar Flare",1265,2,"Cost"),
	SKILL_3_SOLAR_FLARE("Solar Flare",1265,3,"Holy Attack"),
	SKILL_1_SOLAR_FLARE("Solar Flare",1265,1,"Power"),
	SKILL_2_SONG_OF_CHAMPION("Song of Champion",364,2,"Cost"),
	SKILL_1_SONG_OF_CHAMPION("Song of Champion",364,1,"Time"),
	SKILL_2_SONG_OF_EARTH("Song of Earth",264,2,"Cost"),
	SKILL_1_SONG_OF_EARTH("Song of Earth",264,1,"Time"),
	SKILL_2_SONG_OF_ELEMENTAL("Song of Elemental",529,2,"Cost"),
	SKILL_1_SONG_OF_ELEMENTAL("Song of Elemental",529,1,"Time"),
	SKILL_2_SONG_OF_FLAME_GUARD("Song of Flame Guard",306,2,"Cost"),
	SKILL_1_SONG_OF_FLAME_GUARD("Song of Flame Guard",306,1,"Time"),
	SKILL_2_SONG_OF_HUNTER("Song of Hunter",269,2,"Cost"),
	SKILL_1_SONG_OF_HUNTER("Song of Hunter",269,1,"Time"),
	SKILL_2_SONG_OF_INVOCATION("Song of Invocation",270,2,"Cost"),
	SKILL_1_SONG_OF_INVOCATION("Song of Invocation",270,1,"Time"),
	SKILL_2_SONG_OF_LIFE("Song of Life",265,2,"Cost"),
	SKILL_1_SONG_OF_LIFE("Song of Life",265,1,"Time"),
	SKILL_2_SONG_OF_MEDITATION("Song of Meditation",363,2,"Cost"),
	SKILL_1_SONG_OF_MEDITATION("Song of Meditation",363,1,"Time"),
	SKILL_2_SONG_OF_RENEWAL("Song of Renewal",349,2,"Cost"),
	SKILL_1_SONG_OF_RENEWAL("Song of Renewal",349,1,"Time"),
	SKILL_1_SONG_OF_SILENCE("Song of Silence",437,1,"Chance"),
	SKILL_2_SONG_OF_SILENCE("Song of Silence",437,2,"Cost"),
	SKILL_2_SONG_OF_STORM_GUARD("Song of Storm Guard",308,2,"Cost"),
	SKILL_1_SONG_OF_STORM_GUARD("Song of Storm Guard",308,1,"Time"),
	SKILL_2_SONG_OF_VENGEANCE("Song of Vengeance",305,2,"Cost"),
	SKILL_1_SONG_OF_VENGEANCE("Song of Vengeance",305,1,"Time"),
	SKILL_2_SONG_OF_VITALITY("Song of Vitality",304,2,"Cost"),
	SKILL_1_SONG_OF_VITALITY("Song of Vitality",304,1,"Time"),
	SKILL_2_SONG_OF_WARDING("Song of Warding",267,2,"Cost"),
	SKILL_1_SONG_OF_WARDING("Song of Warding",267,1,"Time"),
	SKILL_2_SONG_OF_WATER("Song of Water",266,2,"Cost"),
	SKILL_1_SONG_OF_WATER("Song of Water",266,1,"Time"),
	SKILL_2_SONG_OF_WIND("Song of Wind",268,2,"Cost"),
	SKILL_1_SONG_OF_WIND("Song of Wind",268,1,"Time"),
	SKILL_2_SONG_OF_WIND_STORM("Song of Wind Storm",764,2,"Cost"),
	SKILL_1_SONG_OF_WIND_STORM("Song of Wind Storm",764,1,"Time"),
	SKILL_7_SONIC_BLASTER("Sonic Blaster",6,7,"Duel"),
	SKILL_6_SONIC_BLASTER("Sonic Blaster",6,6,"Earth Attack"),
	SKILL_3_SONIC_BLASTER("Sonic Blaster",6,3,"Fire Attack"),
	SKILL_2_SONIC_BLASTER("Sonic Blaster",6,2,"Hunting"),
	SKILL_1_SONIC_BLASTER("Sonic Blaster",6,1,"Power"),
	SKILL_4_SONIC_BLASTER("Sonic Blaster",6,4,"Water Attack"),
	SKILL_5_SONIC_BLASTER("Sonic Blaster",6,5,"Wind Attack"),
	SKILL_2_SONIC_BUSTER("Sonic Buster",9,2,"Cost"),
	SKILL_7_SONIC_BUSTER("Sonic Buster",9,7,"Duel"),
	SKILL_6_SONIC_BUSTER("Sonic Buster",9,6,"Earth Attack"),
	SKILL_3_SONIC_BUSTER("Sonic Buster",9,3,"Fire Attack"),
	SKILL_1_SONIC_BUSTER("Sonic Buster",9,1,"Power"),
	SKILL_4_SONIC_BUSTER("Sonic Buster",9,4,"Water Attack"),
	SKILL_5_SONIC_BUSTER("Sonic Buster",9,5,"Wind Attack"),
	SKILL_2_SONIC_STORM("Sonic Storm",7,2,"Cost"),
	SKILL_7_SONIC_STORM("Sonic Storm",7,7,"Duel"),
	SKILL_6_SONIC_STORM("Sonic Storm",7,6,"Earth Attack"),
	SKILL_3_SONIC_STORM("Sonic Storm",7,3,"Fire Attack"),
	SKILL_1_SONIC_STORM("Sonic Storm",7,1,"Power"),
	SKILL_4_SONIC_STORM("Sonic Storm",7,4,"Water Attack"),
	SKILL_5_SONIC_STORM("Sonic Storm",7,5,"Wind Attack"),
	SKILL_2_SOUL_BARRIER("Soul Barrier",1514,2,"Defense"),
	SKILL_1_SOUL_BARRIER("Soul Barrier",1514,1,"Time"),
	SKILL_1_SOUL_BREAKER("Soul Breaker",281,1,"Chance"),
	SKILL_2_SOUL_BREAKER("Soul Breaker",281,2,"Cost"),
	SKILL_3_SOUL_BREAKER("Soul Breaker",281,3,"Defense"),
	SKILL_4_SOUL_BREAKER("Soul Breaker",281,4,"Magic Defense"),
	SKILL_1_SOUL_CRY("Soul Cry",1001,1,"Power"),
	SKILL_1_SOUL_GATHERING("Soul Gathering",625,1,"Cost"),
	SKILL_2_SOUL_GATHERING("Soul Gathering",625,2,"Recycle"),
	SKILL_1_SOUL_GUARD("Soul Guard",1283,1,"Power"),
	SKILL_1_SOUL_HARMONY("Soul Harmony",1480,1,"Cost"),
	SKILL_3_SOUL_HARMONY("Soul Harmony",1480,3,"Recycle"),
	SKILL_2_SOUL_HARMONY("Soul Harmony",1480,2,"Time"),
	SKILL_2_SOUL_OF_PAAGRIO("Soul of Pa agrio",1365,2,"Cost"),
	SKILL_1_SOUL_OF_PAAGRIO("Soul of Pa agrio",1365,1,"Time"),
	SKILL_2_SOUL_OF_PAIN("Soul of Pain",1436,2,"Cost"),
	SKILL_3_SOUL_OF_PAIN("Soul of Pain",1436,3,"Dark Attack"),
	SKILL_4_SOUL_OF_PAIN("Soul of Pain",1436,4,"Duel"),
	SKILL_1_SOUL_OF_PAIN("Soul of Pain",1436,1,"Power"),
	SKILL_1_SOUL_OF_SAGITTARIUS("Soul of Sagittarius",303,1,"Cost"),
	SKILL_2_SOUL_SHIELD("Soul Shield",1010,2,"Cost"),
	SKILL_1_SOUL_SHIELD("Soul Shield",1010,1,"Time"),
	SKILL_4_SOUL_SHOCK("Soul Shock",627,4,"Chance"),
	SKILL_2_SOUL_SHOCK("Soul Shock",627,2,"Cost"),
	SKILL_1_SOUL_SHOCK("Soul Shock",627,1,"Power"),
	SKILL_3_SOUL_SHOCK("Soul Shock",627,3,"Time"),
	SKILL_2_SOUL_STRIKE("Soul Strike",1516,2,"Duel"),
	SKILL_1_SOUL_STRIKE("Soul Strike",1516,1,"Power"),
	SKILL_3_SOUL_VORTEX("Soul Vortex",1512,3,"Chance"),
	SKILL_2_SOUL_VORTEX("Soul Vortex",1512,2,"Cost"),
	SKILL_4_SOUL_VORTEX("Soul Vortex",1512,4,"Duel"),
	SKILL_1_SOUL_VORTEX("Soul Vortex",1512,1,"Power"),
	SKILL_2_SOUL_VORTEX_EXTINCTION("Soul Vortex Extinction",1513,2,"Cost"),
	SKILL_3_SOUL_VORTEX_EXTINCTION("Soul Vortex Extinction",1513,3,"Duel"),
	SKILL_1_SOUL_VORTEX_EXTINCTION("Soul Vortex Extinction",1513,1,"Power"),
	SKILL_2_SOUL_WEB("Soul Web",1529,2,"Chance"),
	SKILL_1_SOUL_WEB("Soul Web",1529,1,"Cost"),
	SKILL_3_SOUL_WEB("Soul Web",1529,3,"Time"),
	SKILL_2_SPIRIT_BARRIER("Spirit Barrier",123,2,"Cost"),
	SKILL_1_SPIRIT_BARRIER("Spirit Barrier",123,1,"Time"),
	SKILL_2_SPITE("Spite",1485,2,"Chance"),
	SKILL_1_SPITE("Spite",1485,1,"Cost"),
	SKILL_3_SPOIL("Spoil",254,3,"Earth Vulnerability"),
	SKILL_1_SPOIL("Spoil",254,1,"Power"),
	SKILL_3_SPOIL_FESTIVAL("Spoil Festival",302,3,"Earth Vulnerability"),
	SKILL_1_SPOIL_FESTIVAL("Spoil Festival",302,1,"Power"),
	SKILL_2_SPREAD_WING("Spread Wing",492,2,"Cost"),
	SKILL_1_SPREAD_WING("Spread Wing",492,1,"Power"),
	SKILL_2_SPRINT("Sprint",230,2,"Cost"),
	SKILL_3_SPRINT("Sprint",230,3,"Dodge"),
	SKILL_4_SPRINT("Sprint",230,4,"Freedom"),
	SKILL_1_SPRINT("Sprint",230,1,"Time"),
	SKILL_2_STEAL_ESSENCE("Steal Essence",1245,2,"Cost"),
	SKILL_1_STEAL_ESSENCE("Steal Essence",1245,1,"Power"),
	SKILL_3_STEAL_ESSENCE("Steal Essence",1245,3,"Sap"),
	SKILL_1_STEALTH("Stealth",411,1,"Cost"),
	SKILL_2_STEALTH("Stealth",411,2,"Time"),
	SKILL_1_STIGMA_OF_SHILIEN("Stigma of Shilien",1539,1,"Time"),
	SKILL_1_STING("Sting",223,1,"Chance"),
	SKILL_2_STING("Sting",223,2,"Cost"),
	SKILL_2_STORM_ASSAULT("Storm Assault",493,2,"Cost"),
	SKILL_7_STORM_ASSAULT("Storm Assault",493,7,"Duel"),
	SKILL_6_STORM_ASSAULT("Storm Assault",493,6,"Earth Attack"),
	SKILL_3_STORM_ASSAULT("Storm Assault",493,3,"Fire Attack"),
	SKILL_1_STORM_ASSAULT("Storm Assault",493,1,"Power"),
	SKILL_4_STORM_ASSAULT("Storm Assault",493,4,"Water Attack"),
	SKILL_5_STORM_ASSAULT("Storm Assault",493,5,"Wind Attack"),
	SKILL_1_STUN_ATTACK("Stun Attack",100,1,"Power"),
	SKILL_1_STUN_SHOT("Stun Shot",101,1,"Chance"),
	SKILL_2_STUN_SHOT("Stun Shot",101,2,"Cost"),
	SKILL_3_STUN_SHOT("Stun Shot",101,3,"Defense"),
	SKILL_4_STUN_SHOT("Stun Shot",101,4,"Magic Defense"),
	SKILL_1_SUMMON_AQUA_CUBIC("Summon Aqua Cubic",1280,1,"Power"),
	SKILL_1_SUMMON_ATTRACTIVE_CUBIC("Summon Attractive Cubic",449,1,"Power"),
	SKILL_1_SUMMON_BIG_BOOM("Summon Big Boom",301,1,"Power"),
	SKILL_1_SUMMON_BINDING_CUBIC("Summon Binding Cubic",1279,1,"Power"),
	SKILL_1_SUMMON_BOXER_THE_UNICORN("Summon Boxer the Unicorn",1226,1,"Power"),
	SKILL_1_SUMMON_CORRUPTED_MAN("Summon Corrupted Man",1154,1,"Power"),
	SKILL_1_SUMMON_CURSED_MAN("Summon Cursed Man",1334,1,"Power"),
	SKILL_1_SUMMON_DARK_PANTHER("Summon Dark Panther",283,1,"Power"),
	SKILL_1_SUMMON_FELINE_KING("Summon Feline King",1406,1,"Power"),
	SKILL_1_SUMMON_FELINE_QUEEN("Summon Feline Queen",1331,1,"Power"),
	SKILL_1_SUMMON_KAI_THE_CAT("Summon Kai the Cat",1276,1,"Power"),
	SKILL_1_SUMMON_KAT_THE_CAT("Summon Kat the Cat",1111,1,"Power"),
	SKILL_1_SUMMON_LIFE_CUBIC("Summon Life Cubic",67,1,"Power"),
	SKILL_1_SUMMON_LORE("Summon Lore",435,1,"Power"),
	SKILL_1_SUMMON_MAGNUS_THE_UNICORN("Summon Magnus the Unicorn",1407,1,"Power"),
	SKILL_1_SUMMON_MECHANIC_GOLEM("Summon Mechanic Golem",25,1,"Power"),
	SKILL_1_SUMMON_MERROW_THE_UNICORN("Summon Merrow the Unicorn",1277,1,"Power"),
	SKILL_1_SUMMON_MEW_THE_CAT("Summon Mew the Cat",1225,1,"Power"),
	SKILL_1_SUMMON_MIRAGE_THE_UNICORN("Summon Mirage the Unicorn",1227,1,"Power"),
	SKILL_1_SUMMON_NIGHTSHADE("Summon Nightshade",1333,1,"Power"),
	SKILL_1_SUMMON_PHANTOM_CUBIC("Summon Phantom Cubic",33,1,"Power"),
	SKILL_1_SUMMON_REANIMATED_MAN("Summon Reanimated Man",1129,1,"Power"),
	SKILL_1_SUMMON_SERAPHIM_THE_UNICORN("Summon Seraphim the Unicorn",1332,1,"Power"),
	SKILL_1_SUMMON_SHADOW("Summon Shadow",1128,1,"Power"),
	SKILL_1_SUMMON_SIEGE_GOLEM("Summon Siege Golem",13,1,"Power"),
	SKILL_1_SUMMON_SILHOUETTE("Summon Silhouette",1228,1,"Power"),
	SKILL_1_SUMMON_SOULLESS("Summon Soulless",1278,1,"Power"),
	SKILL_1_SUMMON_SPARK_CUBIC("Summon Spark Cubic",1281,1,"Power"),
	SKILL_1_SUMMON_SPECTRAL_LORD("Summon Spectral Lord",1408,1,"Power"),
	SKILL_1_SUMMON_STORM_CUBIC("Summon Storm Cubic",10,1,"Power"),
	SKILL_1_SUMMON_SWOOP_CANNON("Summon Swoop Cannon",448,1,"Power"),
	SKILL_1_SUMMON_VAMPIRIC_CUBIC("Summon Vampiric Cubic",22,1,"Power"),
	SKILL_1_SUMMON_VIPER_CUBIC("Summon Viper Cubic",278,1,"Power"),
	SKILL_1_SUMMON_WILD_HOG_CANNON("Summon Wild Hog Cannon",299,1,"Power"),
	SKILL_2_SURRENDER_TO_DARK("Surrender to Dark",1445,2,"Chance"),
	SKILL_1_SURRENDER_TO_DARK("Surrender to Dark",1445,1,"Power"),
	SKILL_3_SURRENDER_TO_DARK("Surrender to Dark",1445,3,"Time"),
	SKILL_1_SURRENDER_TO_EARTH("Surrender To Earth",1223,1,"Chance"),
	SKILL_2_SURRENDER_TO_EARTH("Surrender To Earth",1223,2,"Cost"),
	SKILL_3_SURRENDER_TO_EARTH("Surrender To Earth",1223,3,"Earth Weakness"),
	SKILL_1_SURRENDER_TO_FIRE("Surrender To Fire",1083,1,"Chance"),
	SKILL_2_SURRENDER_TO_FIRE("Surrender To Fire",1083,2,"Cost"),
	SKILL_3_SURRENDER_TO_FIRE("Surrender To Fire",1083,3,"Fire Weakness"),
	SKILL_1_SURRENDER_TO_POISON("Surrender To Poison",1224,1,"Chance"),
	SKILL_2_SURRENDER_TO_POISON("Surrender To Poison",1224,2,"Cost"),
	SKILL_3_SURRENDER_TO_POISON("Surrender To Poison",1224,3,"Power"),
	SKILL_1_SURRENDER_TO_WATER("Surrender To Water",1071,1,"Chance"),
	SKILL_2_SURRENDER_TO_WATER("Surrender To Water",1071,2,"Cost"),
	SKILL_3_SURRENDER_TO_WATER("Surrender To Water",1071,3,"Water Weakness"),
	SKILL_1_SURRENDER_TO_WIND("Surrender To Wind",1074,1,"Chance"),
	SKILL_2_SURRENDER_TO_WIND("Surrender To Wind",1074,2,"Cost"),
	SKILL_3_SURRENDER_TO_WIND("Surrender To Wind",1074,3,"Wind Weakness"),
	SKILL_1_SWEEPER("Sweeper",42,1,"HPPower"),
	SKILL_2_SWEEPER("Sweeper",42,2,"MPPower"),
	SKILL_2_SWORD_SHIELD("Sword Shield",483,2,"Movement"),
	SKILL_1_SWORD_SHIELD("Sword Shield",483,1,"Power"),
	SKILL_2_TEMPEST("Tempest",1176,2,"Cost"),
	SKILL_1_TEMPEST("Tempest",1176,1,"Power"),
	SKILL_3_TEMPEST("Tempest",1176,3,"Wind Attack"),
	SKILL_2_THE_GLORY_OF_PAAGRIO("The Glory of Pa agrio",1008,2,"Cost"),
	SKILL_1_THE_GLORY_OF_PAAGRIO("The Glory of Pa agrio",1008,1,"Time"),
	SKILL_2_THE_HEART_OF_PAAGRIO("The Heart of Pa agrio",1256,2,"Cost"),
	SKILL_1_THE_HEART_OF_PAAGRIO("The Heart of Pa agrio",1256,1,"Power"),
	SKILL_2_THE_HONOR_OF_PAAGRIO("The Honor of Pa agrio",1305,2,"Cost"),
	SKILL_1_THE_HONOR_OF_PAAGRIO("The Honor of Pa agrio",1305,1,"Power"),
	SKILL_2_THE_TACT_OF_PAAGRIO("The Tact of Pa agrio",1260,2,"Cost"),
	SKILL_1_THE_TACT_OF_PAAGRIO("The Tact of Pa agrio",1260,1,"Time"),
	SKILL_2_THE_VISION_OF_PAAGRIO("The Vision of Pa agrio",1249,2,"Cost"),
	SKILL_1_THE_VISION_OF_PAAGRIO("The Vision of Pa agrio",1249,1,"Time"),
	SKILL_2_THE_WISDOM_OF_PAAGRIO("The Wisdom of Pa agrio",1004,2,"Cost"),
	SKILL_1_THE_WISDOM_OF_PAAGRIO("The Wisdom of Pa agrio",1004,1,"Time"),
	SKILL_2_THIN_SKIN("Thin Skin",1483,2,"Chance"),
	SKILL_1_THIN_SKIN("Thin Skin",1483,1,"Cost"),
	SKILL_1_THRILL_FIGHT("Thrill Fight",130,1,"Cost"),
	SKILL_2_THRONE_OF_ICE("Throne of Ice",1455,2,"Cost"),
	SKILL_1_THRONE_OF_ICE("Throne of Ice",1455,1,"Power"),
	SKILL_3_THRONE_OF_ICE("Throne of Ice",1455,3,"Water Attack"),
	SKILL_2_THRONE_OF_WIND("Throne of Wind",1458,2,"Cost"),
	SKILL_1_THRONE_OF_WIND("Throne of Wind",1458,1,"Power"),
	SKILL_3_THRONE_OF_WIND("Throne of Wind",1458,3,"Wind Attack"),
	SKILL_1_THUNDER_STORM("Thunder Storm",48,1,"Chance"),
	SKILL_2_THUNDER_STORM("Thunder Storm",48,2,"Cost"),
	SKILL_2_TOUCH_OF_DEATH("Touch of Death",342,2,"Chance"),
	SKILL_1_TOUCH_OF_DEATH("Touch of Death",342,1,"Cost"),
	SKILL_1_TOUCH_OF_LIFE("Touch of Life",341,1,"Cost"),
	SKILL_2_TOUCH_OF_LIFE("Touch of Life",341,2,"Time"),
	SKILL_1_TOUGHNESS("Toughness",134,1,"Power"),
	SKILL_2_TRANCE("Trance",1394,2,"Chance"),
	SKILL_1_TRANCE("Trance",1394,1,"Time"),
	SKILL_1_TRANSFER_PAIN("Transfer Pain",1262,1,"Power"),
	SKILL_2_TRIBUNAL("Tribunal",400,2,"Cost"),
	SKILL_4_TRIBUNAL("Tribunal",400,4,"Holy Attack"),
	SKILL_3_TRIBUNAL("Tribunal",400,3,"Modify Critical"),
	SKILL_1_TRIBUNAL("Tribunal",400,1,"Power"),
	SKILL_2_TRIPLE_SLASH("Triple Slash",1,2,"Cost"),
	SKILL_7_TRIPLE_SLASH("Triple Slash",1,7,"Duel"),
	SKILL_6_TRIPLE_SLASH("Triple Slash",1,6,"Earth Attack"),
	SKILL_3_TRIPLE_SLASH("Triple Slash",1,3,"Fire Attack"),
	SKILL_1_TRIPLE_SLASH("Triple Slash",1,1,"Power"),
	SKILL_4_TRIPLE_SLASH("Triple Slash",1,4,"Water Attack"),
	SKILL_5_TRIPLE_SLASH("Triple Slash",1,5,"Wind Attack"),
	SKILL_2_TRIPLE_SONIC_SLASH("Triple Sonic Slash",261,2,"Cost"),
	SKILL_7_TRIPLE_SONIC_SLASH("Triple Sonic Slash",261,7,"Duel"),
	SKILL_6_TRIPLE_SONIC_SLASH("Triple Sonic Slash",261,6,"Earth Attack"),
	SKILL_3_TRIPLE_SONIC_SLASH("Triple Sonic Slash",261,3,"Fire Attack"),
	SKILL_1_TRIPLE_SONIC_SLASH("Triple Sonic Slash",261,1,"Power"),
	SKILL_4_TRIPLE_SONIC_SLASH("Triple Sonic Slash",261,4,"Water Attack"),
	SKILL_5_TRIPLE_SONIC_SLASH("Triple Sonic Slash",261,5,"Wind Attack"),
	SKILL_2_TRIPLE_THRUST("Triple Thrust",504,2,"Cost"),
	SKILL_7_TRIPLE_THRUST("Triple Thrust",504,7,"Duel"),
	SKILL_6_TRIPLE_THRUST("Triple Thrust",504,6,"Earth Attack"),
	SKILL_3_TRIPLE_THRUST("Triple Thrust",504,3,"Fire Attack"),
	SKILL_1_TRIPLE_THRUST("Triple Thrust",504,1,"Power"),
	SKILL_4_TRIPLE_THRUST("Triple Thrust",504,4,"Water Attack"),
	SKILL_5_TRIPLE_THRUST("Triple Thrust",504,5,"Wind Attack"),
	SKILL_2_TRUE_BERSERKER("True Berserker",500,2,"Cost"),
	SKILL_1_TRUE_BERSERKER("True Berserker",500,1,"Power"),
	SKILL_3_TURN_UNDEAD("Turn Undead",1400,3,"Attack"),
	SKILL_2_TURN_UNDEAD("Turn Undead",1400,2,"Cost"),
	SKILL_4_TURN_UNDEAD("Turn Undead",1400,4,"Holy Attack"),
	SKILL_1_TURN_UNDEAD("Turn Undead",1400,1,"Power"),
	SKILL_2_TWIN_SHOT("Twin Shot",507,2,"Cost"),
	SKILL_7_TWIN_SHOT("Twin Shot",507,7,"Duel"),
	SKILL_6_TWIN_SHOT("Twin Shot",507,6,"Earth Attack"),
	SKILL_3_TWIN_SHOT("Twin Shot",507,3,"Fire Attack"),
	SKILL_1_TWIN_SHOT("Twin Shot",507,1,"Power"),
	SKILL_4_TWIN_SHOT("Twin Shot",507,4,"Water Attack"),
	SKILL_5_TWIN_SHOT("Twin Shot",507,5,"Wind Attack"),
	SKILL_3_ULTIMATE_DEFENSE("Ultimate Defense",110,3,"Decrease Penalty"),
	SKILL_2_ULTIMATE_DEFENSE("Ultimate Defense",110,2,"Recycle"),
	SKILL_1_ULTIMATE_DEFENSE("Ultimate Defense",110,1,"Time"),
	SKILL_2_ULTIMATE_EVASION("Ultimate Evasion",111,2,"Recycle"),
	SKILL_1_ULTIMATE_EVASION("Ultimate Evasion",111,1,"Time"),
	SKILL_2_VAMPIRIC_CLAW("Vampiric Claw",1234,2,"Cost"),
	SKILL_4_VAMPIRIC_CLAW("Vampiric Claw",1234,4,"Dark Attack"),
	SKILL_1_VAMPIRIC_CLAW("Vampiric Claw",1234,1,"Power"),
	SKILL_3_VAMPIRIC_CLAW("Vampiric Claw",1234,3,"Sap"),
	SKILL_1_VAMPIRIC_IMPULSE("Vampiric Impulse",1477,1,"Cost"),
	SKILL_3_VAMPIRIC_IMPULSE("Vampiric Impulse",1477,3,"Recycle"),
	SKILL_2_VAMPIRIC_IMPULSE("Vampiric Impulse",1477,2,"Time"),
	SKILL_2_VAMPIRIC_RAGE("Vampiric Rage",1268,2,"Cost"),
	SKILL_1_VAMPIRIC_RAGE("Vampiric Rage",1268,1,"Time"),
	SKILL_2_VENGEANCE("Vengeance",368,2,"Decrease Penalty"),
	SKILL_1_VENGEANCE("Vengeance",368,1,"Power"),
	SKILL_3_VENGEANCE("Vengeance",368,3,"Recovery"),
	SKILL_2_VICIOUS_STANCE("Vicious Stance",312,2,"Cost"),
	SKILL_1_VICIOUS_STANCE("Vicious Stance",312,1,"Power"),
	SKILL_2_VICTORY_OF_PAAGRIO("Victory of Pa agrio",1414,2,"Cost"),
	SKILL_3_VICTORY_OF_PAAGRIO("Victory of Pa agrio",1414,3,"Decrease Penalty"),
	SKILL_1_VICTORY_OF_PAAGRIO("Victory of Pa agrio",1414,1,"Time"),
	SKILL_1_VIOLENT_TEMPER("Violent Temper",501,1,"Chance"),
	SKILL_2_VIOLENT_TEMPER("Violent Temper",501,2,"Time"),
	SKILL_2_VITALIZE("Vitalize",1020,2,"Cost"),
	SKILL_1_VITALIZE("Vitalize",1020,1,"Power"),
	SKILL_1_VOICE_BIND("Voice Bind",1447,1,"Chance"),
	SKILL_2_VOICE_BIND("Voice Bind",1447,2,"Time"),
	SKILL_1_WAR_CHANT("War Chant",1390,1,"Cost"),
	SKILL_2_WAR_CHANT("War Chant",1390,2,"Time"),
	SKILL_2_WAR_FRENZY("War Frenzy",424,2,"Cost"),
	SKILL_1_WAR_FRENZY("War Frenzy",424,1,"Power"),
	SKILL_2_WARRIOR_SERVITOR("Warrior Servitor",1346,2,"Cost"),
	SKILL_1_WARRIOR_SERVITOR("Warrior Servitor",1346,1,"Time"),
	SKILL_2_WEAK_CONSTITUTION("Weak Constitution",1482,2,"Chance"),
	SKILL_1_WEAK_CONSTITUTION("Weak Constitution",1482,1,"Cost"),
	SKILL_2_WHIRLWIND("Whirlwind",36,2,"Cost"),
	SKILL_7_WHIRLWIND("Whirlwind",36,7,"Duel"),
	SKILL_6_WHIRLWIND("Whirlwind",36,6,"Earth Attack"),
	SKILL_3_WHIRLWIND("Whirlwind",36,3,"Fire Attack"),
	SKILL_1_WHIRLWIND("Whirlwind",36,1,"Power"),
	SKILL_4_WHIRLWIND("Whirlwind",36,4,"Water Attack"),
	SKILL_5_WHIRLWIND("Whirlwind",36,5,"Wind Attack"),
	SKILL_2_WILD_MAGIC("Wild Magic",1303,2,"Cost"),
	SKILL_1_WILD_MAGIC("Wild Magic",1303,1,"Time"),
	SKILL_1_WIND_SHACKLE("Wind Shackle",1206,1,"Chance"),
	SKILL_2_WIND_SHACKLE("Wind Shackle",1206,2,"Cost"),
	SKILL_3_WIND_SHACKLE("Wind Shackle",1206,3,"Wind Vulnerability"),
	SKILL_3_WIND_VORTEX("Wind Vortex",1341,3,"Chance"),
	SKILL_2_WIND_VORTEX("Wind Vortex",1341,2,"Cost"),
	SKILL_1_WIND_VORTEX("Wind Vortex",1341,1,"Power"),
	SKILL_4_WIND_VORTEX("Wind Vortex",1341,4,"Wind Attack"),
	SKILL_2_WIND_VORTEX_SLUG("Wind Vortex Slug",1456,2,"Cost"),
	SKILL_1_WIND_VORTEX_SLUG("Wind Vortex Slug",1456,1,"Power"),
	SKILL_3_WIND_VORTEX_SLUG("Wind Vortex Slug",1456,3,"Wind Attack"),
	SKILL_2_WIND_WALK("Wind Walk",1204,2,"Cost"),
	SKILL_1_WIND_WALK("Wind Walk",1204,1,"Time"),
	SKILL_1_WISDOM("Wisdom",328,1,"Power"),
	SKILL_2_WIZARD_SERVITOR("Wizard Servitor",1347,2,"Cost"),
	SKILL_1_WIZARD_SERVITOR("Wizard Servitor",1347,1,"Time"),
	SKILL_2_WRATH("Wrath",320,2,"Cost"),
	SKILL_1_WRATH("Wrath",320,1,"Power"),
	SKILL_1_ZEALOT("Zealot",420,1,"Cost"),
	SKILL_2_ZEALOT("Zealot",420,2,"Time");

	
	private String skill_name;
	private int skill_id;
	private int skill_path;
	private String skill_pathname;
	
	@SuppressWarnings("unused")
	private static final Logger _log = Logger.getLogger(enum_skill_path_name.class.getName());
	
	private static Map<Integer, HashMap<Integer, String>> SkillNameDirect = new HashMap<Integer, HashMap<Integer, String>>(); 
	
	private enum_skill_path_name(String _name, int _skillid, int _skillpath, String _skillpathname){
		skill_name = _name;
		skill_id = _skillid;
		skill_path = _skillpath;
		skill_pathname = _skillpathname;
	}
	public String getSkillName(){
		return skill_name;
	}
	public int getId(){
		return skill_id;
	}
	public int getIdPath(){
		return skill_path;
	}
	public String getNamePath(){
		return skill_pathname;
	}
	
	
	public static String getPathName(int idSkill, int pathSkill){
		String retorno = "";
		int idPathSkillForSearch = 0;
		if(pathSkill>100){
			int tempPath = Integer.valueOf( String.valueOf(pathSkill).substring(0, 1));
			idPathSkillForSearch = tempPath;
		}else{
			idPathSkillForSearch = pathSkill;
		}		
		if(SkillNameDirect!=null){
			if(SkillNameDirect.containsKey(idSkill)){
				if(SkillNameDirect.get(idSkill).containsKey(idPathSkillForSearch)){
					return SkillNameDirect.get(idSkill).get(idPathSkillForSearch);
				}
			}
		}
		
		try{
			for( enum_skill_path_name temp : values()){
				if(temp.getId() == idSkill && temp.getIdPath() == idPathSkillForSearch){
					retorno = temp.getNamePath();
					break;
				}
			}
		}catch(Exception a){
			
		}
		
		if(SkillNameDirect == null){
			SkillNameDirect.put(idSkill, new HashMap<Integer, String>());
			SkillNameDirect.get(idSkill).put(idPathSkillForSearch, retorno);
		}else if(!SkillNameDirect.containsKey(idSkill)){
			SkillNameDirect.put(idSkill, new HashMap<Integer, String>());
			SkillNameDirect.get(idSkill).put(idPathSkillForSearch, retorno);			
		}else if(SkillNameDirect.containsKey(idSkill)){
			if(!SkillNameDirect.get(idSkill).containsKey(idPathSkillForSearch)){
				SkillNameDirect.get(idSkill).put(idPathSkillForSearch, retorno);				
			}
		}
		
		
		return retorno;
	}
	
}
