package gr.sr.main;

/**
 * @author L2jSunrise Team
 * @Website www.l2jsunrise.com
 */
public class ClassNamesHolder
{
	public static final String getClassName(int classId)
	{
		switch (classId)
		{
			case 0:
				return "人類戰士";
			case 1:
				return "鬥士";
			case 2:
				return "劍鬥士";
			case 3:
				return "傭兵";
			case 4:
				return "騎士";
			case 5:
				return "聖騎士";
			case 6:
				return "闇騎士";
			case 7:
				return "盜賊";
			case 8:
				return "寶藏獵人";
			case 9:
				return "鷹眼";
			case 10:
				return "人類法師";
			case 11:
				return "巫師";
			case 12:
				return "術士";
			case 13:
				return "死靈法師";
			case 14:
				return "法魔";
			case 15:
				return "牧師";
			case 16:
				return "主教";
			case 17:
				return "先知";
			case 18:
				return "精靈戰士";
			case 19:
				return "精靈騎士";
			case 20:
				return "聖殿騎士";
			case 21:
				return "劍術詩人";
			case 22:
				return "精靈巡守";
			case 23:
				return "大地行者";
			case 24:
				return "銀月遊俠";
			case 25:
				return "精靈法師";
			case 26:
				return "精靈巫師";
			case 27:
				return "咒術詩人";
			case 28:
				return "元素使";
			case 29:
				return "精靈神使";
			case 30:
				return "精靈長老";
			case 31:
				return "黑暗精靈戰士";
			case 32:
				return "沼澤騎士";
			case 33:
				return "席琳騎士";
			case 34:
				return "劍刃舞者";
			case 35:
				return "暗殺者";
			case 36:
				return "深淵行者";
			case 37:
				return "闇影遊俠";
			case 38:
				return "黑暗精靈法師";
			case 39:
				return "黑暗巫師";
			case 40:
				return "狂咒術士";
			case 41:
				return "闇影召喚士";
			case 42:
				return "席琳神使";
			case 43:
				return "席琳長老";
			case 44:
				return "半獸人戰士";
			case 45:
				return "突襲者";
			case 46:
				return "破壞者";
			case 47:
				return "武者";
			case 48:
				return "暴君";
			case 49:
				return "半獸人法師";
			case 50:
				return "巫醫";
			case 51:
				return "霸主";
			case 52:
				return "戰狂";
			case 53:
				return "矮人戰士";
			case 54:
				return "收集者";
			case 55:
				return "賞金獵人";
			case 56:
				return "工匠";
			case 57:
				return "戰爭工匠";
			// Third Classes -->
			case 88:
				return "決鬥者";
			case 89:
				return "猛將";
			case 90:
				return "聖凰騎士";
			case 91:
				return "煉獄騎士";
			case 92:
				return "人馬";
			case 93:
				return "冒險英豪";
			case 94:
				return "大魔導士";
			case 95:
				return "魂狩術士";
			case 96:
				return "秘儀召主";
			case 97:
				return "樞機主教";
			case 98:
				return "昭聖者";
			case 99:
				return "伊娃神殿騎士";
			case 100:
				return "伊娃吟遊詩人";
			case 101:
				return "疾風浪人";
			case 102:
				return "月光箭靈";
			case 103:
				return "伊娃秘術詩人";
			case 104:
				return "元素支配者";
			case 105:
				return "伊娃聖者";
			case 106:
				return "席琳冥殿騎士";
			case 107:
				return "幽冥舞者";
			case 108:
				return "魅影獵者";
			case 109:
				return "幽冥箭靈";
			case 110:
				return "暴風狂嘯者";
			case 111:
				return "闇影支配者";
			case 112:
				return "席琳聖者";
			case 113:
				return "泰坦";
			case 114:
				return "卡巴塔里宗師";
			case 115:
				return "君主";
			case 116:
				return "末日戰狂";
			case 117:
				return "財富獵人";
			case 118:
				return "巨匠";
			// Kamael Classes -->
			case 123:
				return "闇天使士兵〔男〕";
			case 124:
				return "闇天使士兵〔女〕";
			case 125:
				return "裝甲突襲兵";
			case 126:
				return "狙擊衛士";
			case 127:
				return "狂戰士";
			case 128:
				return "碎魂者〔男〕";
			case 129:
				return "碎魂者〔女〕";
			case 130:
				return "弩弓遊俠";
			case 131:
				return "末日使者";
			case 132:
				return "追魂使〔男〕";
			case 133:
				return "追魂使〔女〕";
			case 134:
				return "魔彈射手";
			case 135:
				return "戰鬥巡官";
			case 136:
				return "軍武判官";
			default:
				return "Unknown";
		}
	}
}
